'use strict';
// Independent preview: no product API, credentials, storage or model calls.
const paths={
  briefcase:'<rect x="3" y="7" width="18" height="14" rx="2"/><path d="M8 7V5a2 2 0 0 1 2-2h4a2 2 0 0 1 2 2v2M3 12a26 26 0 0 0 18 0M10 12v3h4v-3"/>',
  radar:'<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="5"/><path d="m12 12 7-7"/><circle cx="12" cy="12" r="1"/>',
  list:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 9 1 1 2-2m2 1h3m-8 6 1 1 2-2m2 1h3"/>',
  person:'<circle cx="12" cy="8" r="4"/><path d="M4 21v-2a8 8 0 0 1 16 0v2"/>',
  spark:'<path d="m12 3 2.7 6.3L21 12l-6.3 2.7L12 21l-2.7-6.3L3 12l6.3-2.7Z"/>',
  search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
  filter:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="2" fill="currentColor" stroke="none"/><circle cx="15" cy="17" r="2" fill="currentColor" stroke="none"/>',
  close:'<path d="m6 6 12 12M6 18 18 6"/>',
  arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',
  chevron:'<path d="m6 9 6 6 6-6"/>',
  check:'<path d="m5 12 4 4L19 6"/>',
  warning:'<path d="m12 3 10 18H2Z"/><path d="M12 9v5m0 3v.2"/>',
  shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',
  upload:'<path d="M4 15v5h16v-5M12 16V3m-5 5 5-5 5 5"/>',
  download:'<path d="M4 16v4h16v-4M12 3v13m-5-5 5 5 5-5"/>',
  plus:'<path d="M12 5v14M5 12h14"/>',
  clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>',
  link:'<path d="m10 13 4-4m-6 6-2 2a4 4 0 0 1-6-6l4-4a4 4 0 0 1 6 0m4 2 2-2a4 4 0 0 1 6 6l-4 4a4 4 0 0 1-6 0"/>',
};
const icon=name=>`<svg class="icon" viewBox="0 0 24 24" aria-hidden="true">${paths[name]||paths.briefcase}</svg>`;
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const $=s=>document.querySelector(s);
const jobs=[
  {id:1,title:'后端开发工程师',company:'小红书',cities:['上海','杭州'],tags:['Go','MySQL','Redis'],tier:'优先核对',reason:'后端方向 · 有相关项目依据',state:'DONE',score:78,coverage:86,priority:93,role:'后端开发',summary:'后端方向与意向一致。Go、数据库事务与消息恢复有直接项目依据；高并发系统的实战经验仍需补充。',gap:'大规模线上服务经验',source:'https://job.xiaohongshu.com/campus/position'},
  {id:2,title:'服务端研发工程师',company:'小红书',cities:['上海','北京'],tags:['服务端','Go / C++','分布式'],tier:'优先核对',reason:'服务端与后端同属一个方向',state:'BASIC',score:null,coverage:0,priority:89,role:'后端开发',summary:'标题属于后端方向，技术要求出现 Go 与分布式系统。需要进一步提取岗位要求，核对直接匹配和可迁移经验。',gap:'待模型逐项核对',source:'https://job.xiaohongshu.com/campus/position'},
  {id:3,title:'Agent 平台全栈研发工程师',company:'小红书',cities:['上海','杭州'],tags:['Agent','Python','React'],tier:'值得了解',reason:'Agent 有相关机制，前端经验待核对',state:'STALE',score:46,coverage:72,priority:74,role:'全栈开发',summary:'工具调用与任务调度经验可以迁移到 Agent 平台；Python 与前端工程化尚无足够项目依据。资料已更新，旧结果需要重新核对。',gap:'Python / React 项目依据',source:'https://job.xiaohongshu.com/campus/position'},
  {id:4,title:'安全研发工程师',company:'小红书',cities:['上海','北京'],tags:['Go','Linux','安全'],tier:'值得了解',reason:'研发基础相关，安全领域经验不足',state:'FAILED',score:null,coverage:0,priority:70,role:'安全研发',summary:'Go 与 Linux 有相关依据，安全方向仍需核对。上一轮分析未完成，可单独重试这条岗位。',gap:'安全领域项目经历',source:'https://job.xiaohongshu.com/campus/position'},
  {id:5,title:'基础架构研发工程师',company:'字节跳动',cities:['杭州','深圳'],tags:['Go','Linux','etcd'],tier:'优先核对',reason:'技术栈与基础设施项目相关',state:'DONE',score:73,coverage:83,priority:84,role:'基础架构',summary:'Go、Linux 与服务协调相关事实有直接依据。生产环境容量规划和性能排查仍有信息缺口。',gap:'线上容量规划与性能排查',source:'https://jobs.bytedance.com/'},
  {id:6,title:'云原生开发工程师',company:'阿里巴巴',cities:['杭州'],tags:['Go','Docker','Kubernetes'],tier:'值得了解',reason:'容器部署相关，Kubernetes 待核对',state:'DONE',score:null,coverage:44,priority:68,role:'云原生开发',summary:'Docker 部署经验有依据，但多条 Kubernetes 与集群运维要求尚未找到项目事实。当前依据覆盖度不足，不能可靠给出总分。',gap:'Kubernetes 实践依据',source:'https://talent.alibaba.com/'},
  {id:7,title:'前端开发工程师',company:'小红书',cities:['上海'],tags:['TypeScript','React','CSS'],tier:'方向不同',reason:'与你的后端意向不同',state:'BASIC',score:null,coverage:0,priority:30,role:'前端开发',summary:'目前求职意向为后端开发，技能与项目事实未覆盖主要前端要求。可以保留查看，但不优先消耗模型预算。',gap:'前端开发项目经历',source:'https://job.xiaohongshu.com/campus/position'},
  {id:8,title:'基础平台开发工程师',company:'字节跳动',cities:['上海'],tags:['Go','数据库','平台'],tier:'暂不分析',reason:'岗位已关闭，仍可查看历史',state:'CLOSED',score:null,coverage:0,priority:20,role:'后端开发',summary:'岗位已关闭。当前仅保留示例历史记录，不建议加入新一轮投递分析。',gap:'岗位关闭',source:'https://jobs.bytedance.com/'},
];
const profile={year:'2027',degree:'硕士',major:'软件工程',months:'0',roles:'后端开发',city:'上海',cities:'杭州、广州、深圳',types:'全职、实习',languages:'Go',skills:'Linux、MySQL、Redis、etcd、Docker Compose'};
const factTexts=[
  '使用 Go 实现任务执行器，将任务处理与调度解耦。',
  '使用 MySQL 事务与行锁保证任务状态转换的一致性。',
  '使用 Redis Streams 和确认机制处理消息恢复与重试。',
];
const state={route:'jobs',company:'全部岗位',q:'',city:'',status:'',sort:'priority',onlySelected:false,selected:new Set(),plans:new Set(),model:'DeepSeek',profileTab:'basic',profileDraft:{},detailTab:'summary',detailID:0,round:10,daily:30};
let toastTimer,analysisTimer,modalData=null;
const stateInfo={DONE:['已分析','green'],BASIC:['待分析','gray'],STALE:['待更新','amber'],FAILED:['分析失败','amber'],CLOSED:['已关闭','gray']};
const tierColor=tier=>tier==='优先核对'?'green':tier==='值得了解'?'blue':'gray';
const badge=(text,color='gray')=>`<span class="badge badge-${color}">${esc(text)}</span>`;
function toast(text){clearTimeout(toastTimer);$('#toast').textContent=text;$('#toast').hidden=false;toastTimer=setTimeout(()=>$('#toast').hidden=true,4500);}
function filteredJobs(){return jobs.filter(j=>(state.company==='全部岗位'||j.company===state.company)&&(!state.q||[j.title,j.company,...j.tags].join(' ').toLowerCase().includes(state.q.toLowerCase()))&&(!state.city||j.cities.includes(state.city))&&(!state.status||j.state===state.status)&&(!state.onlySelected||state.selected.has(j.id))).sort((a,b)=>state.sort==='score'?(b.state==='DONE'&&b.score!==null?b.score:-1)-(a.state==='DONE'&&a.score!==null?a.score:-1):b.priority-a.priority);}
function selectionMarkup(){const n=state.selected.size;return `<div class="selection-bar" ${n?'':'hidden'}><div><strong>${n}</strong> 个岗位已选<button class="btn btn-subtle btn-small" data-action="clear">清空</button></div><div><button class="btn" data-action="export">${icon('download')}导出到 ChatGPT</button><button class="btn btn-primary" data-action="analyze">${icon('spark')}深度分析</button></div></div>`;}
function jobRows(){const view=filteredJobs();if(!view.length)return `<div class="empty-state">${icon('search')}<h3>没有找到符合条件的岗位</h3><p>可以换一个关键词，或清除公司、城市和状态筛选。</p><button class="btn" data-action="reset">清除筛选</button></div>`;
  return `<table class="job-table"><thead><tr><th class="check-cell"><input id="select-visible" type="checkbox" aria-label="选择当前筛选结果中的全部岗位" ${view.every(j=>state.selected.has(j.id))?'checked':''}></th><th class="job-cell" scope="col">岗位 / 工作地点</th><th class="tier-cell" scope="col">本地初筛</th><th class="match-cell" scope="col">核心技术匹配</th><th class="state-cell" scope="col">分析状态</th></tr></thead><tbody>${view.map(j=>`<tr class="${state.selected.has(j.id)?'is-selected':''}"><td class="check-cell"><input type="checkbox" data-select="${j.id}" aria-label="选择 ${esc(j.company+' '+j.title)}" ${state.selected.has(j.id)?'checked':''}></td><td class="job-cell"><button class="job-title" data-job="${j.id}"><span class="year">2027 校招</span>${esc(j.title)}</button><div class="job-meta"><span>${esc(j.company)}</span><span class="company-dot"></span><span>${esc(j.cities.join(' / '))}</span><span class="company-dot"></span><span>全职</span></div><div class="job-tags">${j.tags.map(t=>`<span class="tag">${esc(t)}</span>`).join('')}</div></td><td class="tier-cell">${badge(j.tier,tierColor(j.tier))}<span class="tier-note">${esc(j.reason)}</span></td><td class="match-cell">${j.state==='DONE'?(j.score!==null?`<span class="score">${j.score}<small>/ 100</small></span><span class="coverage">依据覆盖 ${j.coverage}%</span>`:`<span class="unscored">依据不足</span><span class="coverage">覆盖 ${j.coverage}% · 暂不评分</span>`):`<span class="unscored">${j.state==='STALE'?'依据变化，待更新':j.state==='CLOSED'?'—':'待深度分析'}</span><span class="coverage">${j.state==='STALE'?'旧结果仅供查看':'初筛建议不能代替匹配度'}</span>`}</td><td class="state-cell">${badge(...stateInfo[j.state])}<span class="date-note">${j.state==='DONE'?'示例分析结果':j.state==='FAILED'?'可单独重试':'今天更新'}</span></td></tr>`).join('')}</tbody></table>`;
}
function updateListing(){const active=document.activeElement,selectID=active?.dataset.select,selectAll=active?.id==='select-visible';const view=filteredJobs();$('#job-rows').innerHTML=jobRows();$('#result-count').textContent=`${view.length} 个岗位`;$('#selection-slot').innerHTML=selectionMarkup();$('#only-selected').checked=state.onlySelected;const box=$('#select-visible');if(box)box.indeterminate=view.some(j=>state.selected.has(j.id))&&!view.every(j=>state.selected.has(j.id));for(const b of document.querySelectorAll('[data-company]'))b.setAttribute('aria-pressed',String(state.company===b.dataset.company));if(selectID)document.querySelector(`[data-select="${selectID}"]`)?.focus();if(selectAll)box?.focus();}
function jobsPage(){return `<div class="page-heading"><div><h1>岗位库</h1><p>选出值得投的岗位，每个判断都有依据。</p></div><div class="heading-actions"><button class="btn" data-open="sources" aria-label="关注来源">${icon('radar')}关注来源</button><button class="btn" data-open="settings" aria-label="分析设置">${icon('filter')}分析设置</button></div></div><section class="workspace-panel" aria-label="岗位筛选与列表"><div class="company-tabs" aria-label="按公司筛选">${['全部岗位','小红书','字节跳动','阿里巴巴'].map(company=>`<button class="company-tab" data-company="${company}" aria-pressed="${state.company===company}">${company}<span class="tab-count">${company==='全部岗位'?jobs.length:jobs.filter(j=>j.company===company).length}</span></button>`).join('')}</div><div class="filterbar"><label class="search-field">${icon('search')}<input id="job-search" type="search" aria-label="搜索公司、岗位或技术" placeholder="搜索公司、岗位或技术" value="${esc(state.q)}"></label><label class="select-field"><span>城市</span><select id="city-filter" aria-label="城市筛选"><option value="">所有城市</option>${['上海','杭州','北京','深圳'].map(c=>`<option ${state.city===c?'selected':''}>${c}</option>`).join('')}</select></label><label class="select-field"><span>状态</span><select id="state-filter" aria-label="分析状态筛选"><option value="">所有状态</option>${Object.entries(stateInfo).map(([s,[name]])=>`<option value="${s}" ${state.status===s?'selected':''}>${name}</option>`).join('')}</select></label><label class="select-field"><select id="sort" aria-label="岗位排序"><option value="priority" ${state.sort==='priority'?'selected':''}>初筛优先</option><option value="score" ${state.sort==='score'?'selected':''}>匹配度优先</option></select></label></div><div class="list-meta"><div><span id="result-count">${filteredJobs().length} 个岗位</span><label class="quiet-check"><input id="only-selected" type="checkbox" ${state.onlySelected?'checked':''}>只看已选</label></div><button class="btn btn-subtle btn-small" data-action="select-top">${icon('plus')}选择优先分析岗位</button></div><div id="job-rows">${jobRows()}</div><div class="table-footer"><span>${icon('shield')}初筛在本地完成，深度分析前核对外发资料</span><span>模型：${esc(state.model)}</span></div></section><div id="selection-slot">${selectionMarkup()}</div>`;}
function field(name,label,value,extra=''){return `<label class="field">${label}<input name="${name}" value="${esc(value)}" ${extra}></label>`;}
function profileContent(){const p={...profile,...state.profileDraft};if(state.profileTab==='basic')return `<h3>基本条件</h3><p>用于核对毕业届别、学历和专业要求。</p><div class="form-grid">${field('year','毕业届别',p.year,'type="number" min="2000" max="2100" required')}<label class="field">最高学历<select name="degree">${['本科','硕士','博士'].map(v=>`<option ${v===p.degree?'selected':''}>${v}</option>`).join('')}</select></label>${field('major','专业',p.major,'required')}${field('months','相关经验（月）',p.months,'type="number" min="0" max="600" required')}</div><div class="note-box">姓名、手机和邮箱无需填入匹配资料。导入简历时在本地识别并遮盖，再由你核对外发文字。</div>`;
  if(state.profileTab==='preferences')return `<h3>求职偏好</h3><p>帮助排列查看顺序，也会单独核对岗位与意向的差异。</p><div class="form-grid">${field('roles','意向职能',p.roles,'required')}${field('types','岗位类型',p.types,'required')}${field('city','首选城市',p.city,'required')}${field('cities','其他可接受城市',p.cities)}</div><div class="note-box">“后端开发”和“服务端开发”会归入相关方向。城市偏好与岗位硬性资格分别展示，避免混淆。</div>`;
  return `<h3>技能与项目</h3><p>技术标签便于初筛，已确认的项目事实支撑深度分析。</p><div class="form-grid">${field('languages','掌握的语言',p.languages,'required')}${field('skills','技术与工具',p.skills)}</div><div class="skill-group"><h4>当前技能</h4><div class="skill-chips">${[...p.languages.split(/[、,]/),...p.skills.split(/[、,]/)].filter(Boolean).map(t=>`<span>${esc(t.trim())}</span>`).join('')}</div></div><div class="section-title"><h3>项目经历</h3><button type="button" class="text-btn" data-open="add-project">添加项目</button></div><details class="project-preview" open><summary><span>任务调度与消息恢复平台<small>后端项目 · ${factTexts.length} 条已确认事实</small></span><span class="chevron">${icon('chevron')}</span></summary>${factTexts.map(t=>`<div class="fact-item">${badge('已实现','green')} ${badge('已确认')}<p>${esc(t)}</p><small>依据：示例简历项目描述</small></div>`).join('')}</details><details class="project-preview"><summary><span>待补充的实践<small>局限与计划单独记录，不当作已完成成果</small></span><span class="chevron">${icon('chevron')}</span></summary><div class="fact-item">${badge('计划','amber')}<p>补充 Kubernetes 集群部署与监控实践。</p><small>计划不进入已实现成果的匹配依据。</small></div></details>`;
}
function profilePage(){return `<div class="page-heading"><div><h1>求职资料</h1><p>你的条件、偏好和项目，是匹配岗位的依据。</p></div><div class="heading-actions"><button class="btn btn-primary" data-open="resume" aria-label="导入简历">${icon('upload')}导入简历</button></div></div><div class="settings-layout"><section class="settings-panel"><div class="profile-tabs" role="tablist" aria-label="求职资料分区">${[['basic','基本条件'],['preferences','求职偏好'],['skills','技能与项目']].map(([id,label])=>`<button id="profile-tab-${id}" type="button" role="tab" aria-selected="${state.profileTab===id}" aria-controls="profile-panel" tabindex="${state.profileTab===id?'0':'-1'}" data-profile-tab="${id}">${label}</button>`).join('')}</div><form id="profile-form"><div id="profile-panel" class="settings-body" role="tabpanel" aria-labelledby="profile-tab-${state.profileTab}">${profileContent()}</div><div class="settings-actions"><span>修改后需要保存 · 仅作用于本次预览</span><button class="btn btn-primary">保存${state.profileTab==='basic'?'基本条件':state.profileTab==='preferences'?'求职偏好':'技能与项目'}</button></div></form></section><aside class="side-info"><h3>这些资料如何使用</h3><div class="info-line">${icon('check')}基本条件核对投递资格</div><div class="info-line">${icon('check')}意向与技术用于本地初筛</div><div class="info-line">${icon('check')}项目事实用于逐项匹配</div><div class="side-rule"></div><p>模型提取的是草稿。你逐项确认并保存后，才会成为匹配依据。</p><div class="note-box">${icon('shield')}<p style="margin-top:8px">简历原文件和联系方式保留在本地。每次外发前，都能核对完整的脱敏文字。</p></div></aside></div>`;}
function modelsPage(){return `<div class="page-heading"><div><h1>模型设置</h1><p>选择服务商，分析时直接使用已配置的模型。</p></div></div><div class="settings-layout"><section class="settings-panel"><div class="settings-body"><h3>外部模型</h3><p>常用服务商内置预设，无需手动填写接口地址。</p><div class="model-list">${['DeepSeek','GPT'].map(m=>`<label class="model-option"><input name="provider" type="radio" value="${m}" ${m===state.model?'checked':''}><div class="provider-mark">${m==='GPT'?'G':'D'}</div><span>${m}<small>${m==='GPT'?'OpenAI API':'DeepSeek API'}</small></span></label>`).join('')}</div><label class="field">模型<select id="model-name" aria-label="模型预设"><option>${state.model==='GPT'?'GPT · 预设模型':'DeepSeek · 预设模型'}</option></select></label><label class="field">API 密钥<input type="password" disabled placeholder="设计预览不接收或保存密钥" autocomplete="off"></label><p class="field-help">正式版在这里填写密钥，保留在本机。分析请求使用所选服务商的 API；订阅和 API 费用分别结算。</p><div class="note-box">当前为交互预览。不会检查密钥、连接服务商或消耗 API 额度。</div></div><div class="settings-actions"><span>本次预览：${esc(state.model)}</span><button class="btn btn-primary" data-action="save-model">使用这个预设</button></div></section><aside class="side-info"><h3>你掌握发送时机</h3><div class="info-line">${icon('shield')}密钥不会显示在外发资料里</div><p>配置模型之后，仍需在发起分析时核对脱敏资料。切换服务商不会自动发送任何内容。</p><div class="side-rule"></div><h3>也可以用 ChatGPT 聊天</h3><p>在岗位库选择岗位，导出已核对的分析包，再手动上传到 ChatGPT。这个方式无需配置 API 密钥。</p></aside></div>`;}
function renderRoute(){const form=$('#profile-form');if(form)for(const [k,v] of new FormData(form))state.profileDraft[k]=String(v);state.route=['jobs','profile','models'].includes(location.hash.slice(1))?location.hash.slice(1):'jobs';const names={jobs:'岗位库',profile:'求职资料',models:'模型设置'};document.title=names[state.route]+' · CampusTrace 设计预览';$('#crumb').textContent=names[state.route];for(const a of document.querySelectorAll('[data-route]')){if(a.dataset.route===state.route)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');}$('#content').innerHTML=state.route==='profile'?profilePage():state.route==='models'?modelsPage():jobsPage();if(state.route==='jobs')updateListing();}
function modalHead(title,subtitle=''){return `<div class="modal-head"><div><h2 id="modal-title">${title}</h2>${subtitle?`<p>${subtitle}</p>`:''}</div><button class="icon-btn" data-close="modal" aria-label="关闭弹窗">${icon('close')}</button></div>`;}
function openModal(html,wide=false){const modal=$('#modal');modal.classList.toggle('wide',wide);modal.innerHTML=html;if(!modal.open)modal.showModal();}
function getPreviewFacts(){return `毕业届别：${profile.year}\n学历：${profile.degree}\n专业：${profile.major}\n意向职能：${profile.roles}\n岗位类型：${profile.types}\n首选城市：${profile.city}\n其他可接受城市：${profile.cities}\n掌握的语言：${profile.languages}\n技术与工具：${profile.skills}\n\n已确认项目事实：\n${factTexts.map(t=>'• '+t).join('\n')}\n\n以上全部为本次设计预览的示例资料，不包含姓名、手机、邮箱或链接。`;}
function jobOriginal(j){return `【设计预览用示例招聘说明，并非公司真实岗位原文】\n\n${j.title} · ${j.company}\n工作地点：${j.cities.join('、')}\n岗位类型：全职\n\n岗位职责\n参与${j.role}相关系统的设计、开发与维护，完成团队协作中的工程任务。\n\n任职要求\n1. 2027 届本科及以上学历，计算机或相关专业优先。\n2. 掌握 ${j.tags.join('、')} 等相关技术，具备良好的开发基础。\n3. 能清晰说明项目中实际实现的技术机制。\n\n加分项\n具备相关系统的实践经历；${j.gap}可作为进一步核对的方向。`;}
function analysisPacket(ids){return `# CampusTrace 手动分析包 · 设计预览\n\n注意：全部内容为虚构示例，请勿据此判断真实岗位。\n\n## 分析标准\n区分投递资格、核心技术、加分项与软性要求。\n对照事实逐项判断直接匹配、部分匹配、可迁移、明确不匹配或依据不足；不得把计划当作成果，不得把缺少依据当作明确不符合。\n任选要求按同一组核对，不能重复计入核心分数。只对证据覆盖充分的核心技术要求评分，同时报告覆盖度和原文依据。\n\n## 候选人资料\n${getPreviewFacts()}\n\n## 待核对岗位\n${ids.map(id=>jobOriginal(jobs.find(j=>j.id===id))).join('\n\n---\n\n')}`;}
function openReview(kind,ids=[...state.selected]){if(!ids.length){toast('先选择需要分析的岗位。');return;}modalData={kind,ids:[...ids]};const chosen=ids.map(id=>jobs.find(j=>j.id===id));const analyzable=chosen.filter(j=>j.state!=='CLOSED');const isExport=kind==='export';openModal(`${modalHead(isExport?'导出到 ChatGPT':'核对本轮分析资料',isExport?'检查完整分析包，再手动上传到聊天。':'资料核对与确认集中在这一步。')}<div class="modal-body"><div class="steps"><span class="active">选择岗位</span><i></i><span class="active">核对外发资料</span><i></i><span>${isExport?'手动分析':'查看结果'}</span></div><h3>已选 ${chosen.length} 个岗位</h3><div class="review-jobs">${chosen.map(j=>`<div class="review-job"><span>${esc(j.title)}</span><small>${esc(j.company)}${j.state==='CLOSED'?' · 已关闭':j.state==='DONE'?' · 已有结果':''}</small></div>`).join('')}</div>${isExport?`<label class="field">完整分析包<textarea id="packet-text" rows="10">${esc(analysisPacket(ids))}</textarea></label><p class="field-help">正式版会按公司和文字量分包，并保留完整原文。预览只提供本组示例文字。</p>`:`<label class="field">本轮模型<select id="review-model"><option ${state.model==='DeepSeek'?'selected':''}>DeepSeek</option><option ${state.model==='GPT'?'selected':''}>GPT</option></select></label><details class="disclosure" open><summary>查看完整候选人资料与项目事实</summary><div class="source-original">${esc(getPreviewFacts())}</div></details><details class="disclosure"><summary>查看所选岗位的完整文字</summary><div class="source-original">${esc(chosen.map(jobOriginal).join('\n\n---\n\n'))}</div></details>${chosen.some(j=>j.state==='CLOSED')?'<div class="note-box warning">已关闭的岗位将跳过。已分析的岗位展示现有示例结果。</div>':''}<p class="field-help">正式版仅发送脱敏岗位说明和已确认资料；原始简历、联系方式及密钥不进入匹配文字。</p>`}<div class="note-box">本次仅演示${isExport?'导出':'分析'}流程，不发送外部请求、不保存产品数据、不产生费用。</div><label class="check-label"><input type="checkbox" id="review-consent">我已核对全部文字，确认这组${isExport?'示例分析包可以导出':'示例资料可以用于预览分析流程'}。</label></div><div class="modal-foot"><small>${isExport?'下载内容为示例数据':`每轮上限 ${state.round} 个 · 今日上限 ${state.daily} 次（预览）`}</small><div><button class="btn" data-close="modal">取消</button><button class="btn btn-primary" id="review-start" data-action="${isExport?'download-packet':'simulate-analysis'}" disabled ${!isExport&&!analyzable.length?'data-unavailable="true"':''}>${icon(isExport?'download':'spark')}${isExport?'下载示例分析包':'预览分析流程'}</button></div></div>`,true);}
function findingsHTML(j){
  if(j.role==='前端开发')return '<div class="note-box">当前示例资料以 Go 后端为主，未找到 React、TypeScript 或 CSS 的已确认项目事实。</div>';
  if(j.role==='全栈开发')return `<div class="finding">${icon('check')}<div><strong>任务执行与调度经验可迁移</strong><p>有后端任务机制的项目事实，但这不等同于已经实现 Agent 框架或全栈系统。</p></div></div>`;
  return `<div class="finding">${icon('check')}<div><strong>Go 与后端基础</strong><p>示例项目包含 Go 开发、任务处理和数据库机制。具体关系需结合岗位原文核对。</p></div></div><div class="finding">${icon('check')}<div><strong>可解释的工程实践</strong><p>项目事实明确记录事务、消息确认与恢复过程，避免只凭技术标签打分。</p></div></div>`;
}
function summaryHTML(j){const stale=j.state==='STALE',has=j.state==='DONE'&&j.score!==null;return `${j.state==='FAILED'?'<div class="note-box warning">上一轮示例分析失败，尚未产生完整结果。正式版会显示失败阶段及重试操作。</div>':''}${stale?'<div class="note-box warning">分析依据发生变化，旧结果已标记待更新。历史分数不会作为当前匹配度。</div>':''}<section class="result-summary"><div class="result-heading">${has?`<strong class="score-large">${j.score}</strong>`:icon(j.state==='BASIC'?'search':'shield')}<div><h3>${has?'核心技术匹配度':j.state==='DONE'?'依据不足，暂不评分':stale?'需要更新深度分析':'本地初筛结论'}</h3><small>${has||j.state==='DONE'?`依据覆盖 ${j.coverage}% · 示例结果`:j.reason}</small></div></div><p>${esc(j.summary)}</p>${j.state==='DONE'?`<div class="coverage-track" aria-hidden="true"><span style="width:${j.coverage}%"></span></div>`:''}</section><div class="section-title"><h3>已有匹配依据</h3><small>${has?'来自已确认项目事实':'本地关键词与事实摘要'}</small></div>${findingsHTML(j)}<div class="section-title"><h3>需要补充或核对</h3></div><div class="finding gap">${icon('warning')}<div><strong>${esc(j.gap)}</strong><p>暂未找到充分依据；这不等同于明确不符合岗位要求。</p></div></div><details class="disclosure"><summary>投递条件与个人偏好</summary><div class="qualification-list"><div><span>毕业届别</span><b>${esc(profile.year)} 届 · ${profile.year==='2027'?'示例符合':'届别需核对'}</b></div><div><span>学历</span><b>${esc(profile.degree)} · 示例符合</b></div><div><span>岗位方向</span><b>${esc(j.role)}</b></div><div><span>城市偏好</span><b>${j.cities.includes(profile.city)?'包含首选城市':'需结合可接受城市核对'}</b></div></div></details>`;}
function evidenceHTML(j){if(j.role==='前端开发'||j.role==='全栈开发')return `<div class="note-box">${esc(j.role==='前端开发'?'尚无前端项目事实依据。':'后端任务调度经验可迁移，但不能直接证明 Agent 框架或前端能力。')}</div><div class="evidence-item"><div><span>核心要求 · ${esc(j.tags.join(' / '))}</span>${badge('待逐项核对','amber')}</div><p>当前为示例待分析或待更新岗位。正式版完成分析后，再展示新的逐项要求与事实引用。</p></div>`;return `<p class="field-help" style="margin-bottom:18px">以下是证据排版示例。正式版逐条展示岗位原句、个人事实与判断关系。</p><div class="evidence-item"><div><span>核心要求 · Go 开发</span>${badge('直接匹配','green')}</div><p>岗位依据</p><blockquote>掌握 Go 等相关技术，具备良好的开发基础。（示例文字）</blockquote><p>个人依据 · 任务调度与消息恢复平台</p><blockquote>${esc(factTexts[0])}</blockquote></div><div class="evidence-item"><div><span>核心要求 · 数据一致性</span>${badge('部分匹配','blue')}</div><p>个人依据 · 任务调度与消息恢复平台</p><blockquote>${esc(factTexts[1])}</blockquote><p>已实现事务机制；线上数据规模和性能经验尚需核对。</p></div><div class="evidence-item"><div><span>加分项 · ${esc(j.gap)}</span>${badge('依据不足','amber')}</div><p>已确认事实中没有找到足够依据。此项保持未知，不直接判为不符合。</p></div><div class="note-box">仅核心技术要求进入核心分数。资格、加分项与软性要求分别展示；任选能力按同组处理。</div>`;}
function renderDetail(){const j=jobs.find(j=>j.id===state.detailID);if(!j)return;const panel=state.detailTab==='evidence'?evidenceHTML(j):state.detailTab==='source'?`<div class="note-box">以下文字为布局示例，不是实时抓取的岗位原文。</div><div class="source-original">${esc(jobOriginal(j))}</div><div class="section-title"><h3>公开招聘入口</h3></div><a class="text-btn" href="${esc(j.source)}" target="_blank" rel="noreferrer">打开公司招聘网站</a>`:summaryHTML(j);$('#detail').innerHTML=`<div class="drawer-top"><div class="drawer-topline"><span>${esc(j.company)} · 2027 校招</span><button class="icon-btn" data-close="detail" aria-label="关闭岗位详情">${icon('close')}</button></div><h2 id="detail-title">${esc(j.title)}</h2><p class="drawer-subtitle">${esc(j.cities.join(' / '))} · 全职 · 示例数据</p><div class="drawer-actions"><button class="btn btn-primary" data-detail-action="analyze" ${j.state==='CLOSED'?'disabled':''}>${icon('spark')}${j.state==='FAILED'?'重试这条岗位':j.state==='STALE'?'更新分析':'核对匹配'}</button><button class="btn" data-detail-action="plan" ${j.state==='CLOSED'?'disabled':''}>${icon('plus')}${state.plans.has(j.id)?'已加入投递计划':'加入投递计划'}</button></div></div><div class="drawer-body"><div class="detail-tabs" role="tablist" aria-label="岗位详情视图">${[['summary','匹配概览'],['evidence','逐项依据'],['source','岗位原文']].map(([id,name])=>`<button id="detail-tab-${id}" role="tab" aria-selected="${state.detailTab===id}" aria-controls="detail-panel" tabindex="${state.detailTab===id?'0':'-1'}" data-detail-tab="${id}">${name}</button>`).join('')}</div><div id="detail-panel" role="tabpanel" aria-labelledby="detail-tab-${state.detailTab}">${panel}</div></div><div class="drawer-bottom">${j.state==='DONE'?'示例深度分析 · '+esc(j.model||'DeepSeek'):'本地初筛与示例状态'} · 每项判断均可查看来源</div>`;}
function openDetail(id){state.detailID=id;state.detailTab='summary';renderDetail();$('#detail').showModal();}
function openSettings(){openModal(`${modalHead('分析设置','把预算与处理策略放在一个地方。')}<form id="settings-form"><div class="modal-body"><div class="form-grid">${field('round','每轮最多分析岗位数',state.round,'type="number" min="1" max="100" required')}${field('daily','每日调用上限',state.daily,'type="number" min="1" max="200" required')}</div><p class="field-help">正式版顺序处理，命中缓存不再请求模型；失败尝试也计入调用上限。</p><div class="note-box">自动处理只在页面开启且资料已核对时运行。预览不启动后台任务。</div><label class="check-label"><input name="auto" type="checkbox">自动处理新增或变化岗位（流程示意）</label></div><div class="modal-foot"><small>仅调整本次预览</small><div><button type="button" class="btn" data-close="modal">取消</button><button class="btn btn-primary">保存设置</button></div></div></form>`);}
function openSources(){openModal(`${modalHead('关注来源','公司来源集中维护，岗位进入同一个岗位库。')}<div class="modal-body">${[['小红书','5 个示例岗位','https://job.xiaohongshu.com/campus/position'],['字节跳动','2 个示例岗位','https://jobs.bytedance.com/'],['阿里巴巴','1 个示例岗位','https://talent.alibaba.com/']].map(([c,n,url])=>`<div class="source-row"><div><h3>${c}</h3><p>${n} · 展示来源管理布局</p><a href="${url}" target="_blank" rel="noreferrer">公开招聘入口</a></div><button class="btn btn-small" data-source-company="${c}">查看岗位</button></div>`).join('')}<div class="note-box">正式版在这里添加公司校招网址、查看同步结果和失败原因。原型不抓取网站，也不会创建关注记录。</div></div><div class="modal-foot"><small>来源中的岗位会先经过本地初筛</small><button class="btn" data-close="modal">关闭</button></div>`);}
function openPlans(){const plans=jobs.filter(j=>state.plans.has(j.id));openModal(`${modalHead('投递计划','只记录你主动加入的岗位。')}<div class="modal-body">${plans.length?plans.map(j=>`<div class="plan-row"><div><h3>${esc(j.title)}</h3>${badge('计划投递','blue')}</div><p>${esc(j.company)} · ${esc(j.cities.join(' / '))}</p><button class="btn btn-small" data-remove-plan="${j.id}">移出本次示例计划</button></div>`).join(''):`<div class="empty-state">${icon('list')}<h3>还没有投递计划</h3><p>打开岗位详情，把准备申请的岗位加入计划。</p><button class="btn" data-close="modal">去查看岗位</button></div>`}</div><div class="modal-foot"><small>计划仅存在于本次预览</small><button class="btn" data-close="modal">关闭</button></div>`);}
function openResume(step=1){if(step===1)openModal(`${modalHead('从简历整理求职资料','本地读取 → 核对脱敏 → 确认草稿。')}<div class="modal-body"><div class="steps"><span class="active">读取简历</span><i></i><span>核对脱敏</span><i></i><span>确认草稿</span></div><div class="empty-state">${icon('upload')}<h3>简历里的信息，整理到同一份资料</h3><p>正式版支持 PDF、DOCX 和 TXT，在浏览器本地读取。<br>这个预览只加载示例文字，不接收真实简历。</p><button class="btn btn-primary" data-resume-step="2">加载示例简历</button></div><div class="note-box">先识别姓名、手机和邮箱，再由你逐行核对。模型仅提供草稿，不直接覆盖已保存资料。</div></div><div class="modal-foot"><small>原文件始终保留在本地</small><button class="btn" data-close="modal">取消</button></div>`);
  if(step===2)openModal(`${modalHead('核对脱敏文字','只保留与岗位匹配有关的信息。')}<div class="modal-body"><div class="steps"><span>读取简历</span><i></i><span class="active">核对脱敏</span><i></i><span>确认草稿</span></div><label class="field">将用于整理草稿的完整示例文字<textarea id="resume-text" rows="9">姓名：[已遮盖]\n手机：[已遮盖]\n邮箱：[已遮盖]\n\n2027 届软件工程硕士，求职方向为后端开发。\n掌握 Go、MySQL、Redis 和 Linux。\n项目：任务调度与消息恢复平台。\n使用 Go 实现任务执行器；使用 MySQL 事务保证任务状态转换的一致性；使用 Redis Streams 处理消息确认和恢复。</textarea></label><div class="note-box">预览不发送这段文字。正式版还支持补充遮盖姓名，并在发送前检查直接身份信息。</div><label class="check-label"><input id="resume-consent" type="checkbox">我已逐行核对这段示例文字。</label></div><div class="modal-foot"><small>草稿需要逐项确认</small><div><button class="btn" data-resume-step="1">返回</button><button class="btn btn-primary" id="resume-next" data-resume-step="3" disabled>生成示例草稿</button></div></div>`);
  if(step===3)openModal(`${modalHead('确认提取草稿','勾选需要保存的内容，未勾选项不进入资料。')}<div class="modal-body"><div class="steps"><span>读取简历</span><i></i><span>核对脱敏</span><i></i><span class="active">确认草稿</span></div><div class="note-box">以下为预设的演示草稿，没有调用模型。所有项目内容仍需确认真实后保存。</div>${[['year','毕业届别','2027'],['degree','最高学历','硕士'],['roles','意向职能','后端开发'],['languages','掌握的语言','Go']].map(([k,n,v])=>`<label class="draft-line"><input type="checkbox" name="draft" value="${k}"><span>${n}：${v}<small>示例简历有明确文字依据</small></span>${badge('待确认','amber')}</label>`).join('')}<label class="draft-line"><input type="checkbox" name="draft" value="fact"><span>项目事实：使用 Redis Streams 处理消息确认和恢复<small>保存为“已实现”，由你勾选确认</small></span>${badge('待确认','amber')}</label></div><div class="modal-foot"><small>只保存勾选的内容</small><div><button class="btn" data-resume-step="2">返回</button><button class="btn btn-primary" id="save-draft" data-action="save-draft" disabled>保存已确认项</button></div></div>`);}
function openProject(){openModal(`${modalHead('添加项目事实','描述实际实现的机制，而不只是技术名称。')}<form id="project-form"><div class="modal-body">${field('project','项目名称','任务调度与消息恢复平台','readonly required maxlength="200"')}<label class="field">事实内容<textarea name="fact" placeholder="例如：通过事务与行锁保证状态转换一致性。" maxlength="4000" required></textarea></label><label class="check-label"><input type="checkbox" name="verified" required>我已核对这条事实属于实际完成的工作。</label><p class="field-help">本预览将该事实追加到示例项目中，仅保留在当前页面内。</p></div><div class="modal-foot"><button type="button" class="btn" data-close="modal">取消</button><button class="btn btn-primary">保存示例事实</button></div></form>`);}
function simulateAnalysis(){if(!$('#review-consent')?.checked||!modalData)return;const ids=modalData.ids.filter(id=>jobs.find(j=>j.id===id).state!=='CLOSED');if(!ids.length)return;const limit=Math.min(ids.length,state.round);clearTimeout(analysisTimer);modalData={kind:'running',ids:ids.slice(0,limit),paused:false,index:0,model:$('#review-model').value};showProgress();analysisTimer=setTimeout(tickAnalysis,800);}
function showProgress(){const run=modalData;if(!run||run.kind!=='running')return;openModal(`${modalHead('本轮分析进度','演示逐条处理与保存结果，不发送模型请求。')}<div class="modal-body"><div class="progress-panel">${icon('spark')}<h3>${run.paused?'本轮已暂停':`正在核对第 ${Math.min(run.index+1,run.ids.length)} 个岗位`}</h3><p>已完成 ${run.index} / ${run.ids.length} 个示例岗位</p><progress value="${run.index}" max="${run.ids.length}" aria-label="示例分析进度"></progress></div><div class="progress-lines">${run.ids.map((id,i)=>`<div>${icon(i<run.index?'check':'clock')}<span>${esc(jobs.find(j=>j.id===id).title)}</span><small style="margin-left:auto">${i<run.index?'已处理':run.paused?'待继续':'等待处理'}</small></div>`).join('')}</div></div><div class="modal-foot"><small>页面内模拟，不影响真实分析任务</small><div><button class="btn" data-close="modal">关闭</button><button class="btn btn-primary" data-action="${run.paused?'resume-demo':'pause-demo'}">${run.paused?'继续本轮':'暂停后续处理'}</button></div></div>`);}
function tickAnalysis(){const run=modalData;if(!run||run.kind!=='running'||run.paused||!$('#modal').open)return;const j=jobs.find(j=>j.id===run.ids[run.index]);if(j.state!=='DONE'){j.state='DONE';j.model=run.model;j.score=j.tier==='优先核对'?76:null;j.coverage=j.tier==='优先核对'?82:48;j.summary='本条仅演示分析完成状态。正式版会依据实际岗位要求与已确认项目事实，给出逐项判断和覆盖度。';}run.index++;if(run.index===run.ids.length){modalData={kind:'complete',ids:run.ids};if(state.route==='jobs')updateListing();openModal(`${modalHead('本轮示例分析完成','结果已展示在这份原型中。')}<div class="modal-body"><div class="progress-panel">${icon('check')}<h3>已处理 ${run.ids.length} 个示例岗位</h3><p>没有发送模型请求，也没有保存到 CampusTrace。</p></div><div class="note-box">正式版在这里提供成功数、缓存复用数及失败项，并可继续未完成任务或单独重试失败岗位。</div></div><div class="modal-foot"><small>匹配结果为界面示意</small><button class="btn btn-primary" data-action="back-results">查看列表结果</button></div>`);return;}showProgress();analysisTimer=setTimeout(tickAnalysis,1000);}
function downloadPacket(){if(!$('#review-consent')?.checked)return;const text=$('#packet-text').value;const url=URL.createObjectURL(new Blob([text],{type:'text/markdown;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='CampusTrace-设计预览-示例分析包.md';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);$('#modal').close();toast('示例分析包已下载。正式版可以批量分包导出。');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;
  if(b.dataset.close){$('#'+b.dataset.close).close();return;}
  if(b.dataset.company){state.company=b.dataset.company;updateListing();return;}
  if(b.dataset.job){openDetail(Number(b.dataset.job));return;}
  if(b.dataset.profileTab){state.profileTab=b.dataset.profileTab;renderRoute();$('#profile-tab-'+state.profileTab).focus();return;}
  if(b.dataset.detailTab){state.detailTab=b.dataset.detailTab;renderDetail();$('#detail-tab-'+state.detailTab).focus();return;}
  if(b.dataset.detailAction){if(b.dataset.detailAction==='plan'){state.plans.add(state.detailID);$('#plan-count').textContent=state.plans.size;renderDetail();toast('已加入本次示例投递计划。');}else openReview('analyze',[state.detailID]);return;}
  if(b.dataset.sourceCompany){state.company=b.dataset.sourceCompany;state.q='';state.city='';state.status='';state.onlySelected=false;$('#modal').close();location.hash='jobs';renderRoute();return;}
  if(b.dataset.removePlan){state.plans.delete(Number(b.dataset.removePlan));$('#plan-count').textContent=state.plans.size;openPlans();return;}
  if(b.dataset.resumeStep){openResume(Number(b.dataset.resumeStep));return;}
  if(b.dataset.open){const f={settings:openSettings,sources:openSources,applications:openPlans,resume:openResume,'add-project':openProject}[b.dataset.open];if(f)f();return;}
  const a=b.dataset.action;
  if(a==='clear'){state.selected.clear();updateListing();}
  if(a==='select-top'){const top=filteredJobs().filter(j=>j.state!=='DONE'&&j.state!=='CLOSED'&&j.tier!=='方向不同').slice(0,state.round);if(!top.length){toast('当前结果没有待分析的优先岗位。');return;}for(const j of top)state.selected.add(j.id);updateListing();toast(`已选择 ${top.length} 个待分析岗位。可以调整后再发起分析。`);}
  if(a==='reset'){state.company='全部岗位';state.q='';state.city='';state.status='';state.onlySelected=false;renderRoute();}
  if(a==='analyze'||a==='export')openReview(a);
  if(a==='simulate-analysis')simulateAnalysis();
  if(a==='download-packet')downloadPacket();
  if(a==='back-results'){if($('#detail').open)$('#detail').close();$('#modal').close();location.hash='jobs';renderRoute();toast('列表已更新为演示结果，分数仍仅用于设计预览。');}
  if(a==='pause-demo'){clearTimeout(analysisTimer);modalData.paused=true;showProgress();}
  if(a==='resume-demo'){clearTimeout(analysisTimer);modalData.paused=false;showProgress();analysisTimer=setTimeout(tickAnalysis,1000);}
  if(a==='save-model'){toast(`已将 ${state.model} 设为本次预览的默认模型。`);}
  if(a==='save-draft'){const checked=[...document.querySelectorAll('[name="draft"]:checked')].map(i=>i.value);if(!checked.length)return;for(const k of checked)if(k==='fact'){const fact='使用 Redis Streams 处理消息确认和恢复。';if(!factTexts.includes(fact))factTexts.push(fact);}else profile[k]={year:'2027',degree:'硕士',roles:'后端开发',languages:'Go'}[k];$('#modal').close();if(state.route==='profile')renderRoute();toast(`已确认 ${checked.length} 个示例草稿项，真实资料未改变。`);}
});
document.addEventListener('change',e=>{const t=e.target;
  if(t.dataset.select){const id=Number(t.dataset.select);if(t.checked)state.selected.add(id);else state.selected.delete(id);updateListing();return;}
  if(t.id==='select-visible'){for(const j of filteredJobs())if(t.checked)state.selected.add(j.id);else state.selected.delete(j.id);updateListing();return;}
  if(t.id==='city-filter'){state.city=t.value;updateListing();}
  if(t.id==='state-filter'){state.status=t.value;updateListing();}
  if(t.id==='sort'){state.sort=t.value;updateListing();}
  if(t.id==='only-selected'){state.onlySelected=t.checked;updateListing();}
  if(t.id==='review-consent')$('#review-start').disabled=!t.checked||$('#review-start').dataset.unavailable==='true';
  if(t.id==='review-model'){$('#review-consent').checked=false;$('#review-start').disabled=true;}
  if(t.id==='resume-consent')$('#resume-next').disabled=!t.checked;
  if(t.name==='draft')$('#save-draft').disabled=!document.querySelector('[name="draft"]:checked');
  if(t.name==='provider'){state.model=t.value;renderRoute();document.querySelector(`[name="provider"][value="${state.model}"]`).focus();}
});
document.addEventListener('input',e=>{if(e.target.id==='job-search'){state.q=e.target.value.trim();updateListing();}if(e.target.id==='packet-text'){$('#review-consent').checked=false;$('#review-start').disabled=true;}if(e.target.id==='resume-text'){$('#resume-consent').checked=false;$('#resume-next').disabled=true;}});
document.addEventListener('submit',e=>{e.preventDefault();if(!e.target.reportValidity())return;const f=new FormData(e.target);if(e.target.id==='profile-form'){let changed=false;for(const [k,v] of f.entries()){const value=String(v).trim();changed=changed||value!==profile[k];profile[k]=value;delete state.profileDraft[k];}if(changed)for(const j of jobs)if(j.state==='DONE')j.state='STALE';toast('已保存本次预览中的修改，真实求职资料未改变。');}if(e.target.id==='settings-form'){state.round=Number(f.get('round'));state.daily=Number(f.get('daily'));$('#modal').close();toast('本次预览的分析设置已保存。');}if(e.target.id==='project-form'){factTexts.push(String(f.get('fact')).trim());$('#modal').close();state.profileTab='skills';renderRoute();toast('示例项目事实已添加，真实项目记录未改变。');}});
// Arrow keys implement standard tab navigation without introducing extra Tab stops.
document.addEventListener('keydown',e=>{if(!['ArrowLeft','ArrowRight','Home','End'].includes(e.key)||e.target.getAttribute('role')!=='tab')return;const tabs=[...e.target.closest('[role="tablist"]').querySelectorAll('[role="tab"]')];let i=tabs.indexOf(e.target);i=e.key==='Home'?0:e.key==='End'?tabs.length-1:(i+(e.key==='ArrowRight'?1:-1)+tabs.length)%tabs.length;e.preventDefault();tabs[i].click();});
$('#modal').addEventListener('close',()=>{if(modalData?.kind==='running'){clearTimeout(analysisTimer);modalData.paused=true;}});
window.addEventListener('hashchange',renderRoute);
for(const el of document.querySelectorAll('[data-icon]'))el.innerHTML=icon(el.dataset.icon);
renderRoute();
