(function(root){
'use strict';
const kinds={PREFERENCE:'求职偏好',DECISION:'已作决定',CORRECTION:'纠正记录'};
function markup(){return `<details class="agent-panel agent-settings agent-memory"><summary>记忆与讨论记录</summary><p class="meta">只记录你确认过的偏好、决定和纠正。它们不会变成技术能力证明。有效记忆及你选中的讨论摘要会随问答发送给所选模型。</p><form id="memory-editor" novalidate><input type="hidden" name="id"><input type="hidden" name="version"><label>记忆类型<select name="kind">${Object.entries(kinds).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label><label>记住什么<textarea name="content" rows="3" required maxlength="2000" placeholder="例如：主投 Go 后端，优先上海和杭州。不填写姓名、电话等个人信息。"></textarea></label><div class="form-grid"><label>适用范围（可选）<input name="scope" maxlength="200" placeholder="例如：同公司岗位取舍"></label><label>有效天数<input name="days" type="number" min="1" max="3650" value="180" required></label></div><div class="actions"><button>保存这条记忆</button><button type="button" id="memory-reset">取消编辑</button></div></form><div id="memory-list"></div><h3>最近的讨论</h3><p class="meta">摘要有效 30 天；继续时重新查当前记录，不会自动重放操作。遗忘记忆也会清除旧讨论摘要。</p><div id="agent-task-list"></div></details>`}
function preview(v,esc){if(v.forgotten)return '<p>这条记忆已遗忘，重放旧确认不会重新保存。</p>';const a=v.args||v;return `<dl><dt>记忆类型</dt><dd>${esc(kinds[a.kind]||'待核对')}</dd><dt>记住什么</dt><dd class="preserve-lines">${esc(a.content||'')}</dd>${a.scope?`<dt>适用范围</dt><dd>${esc(a.scope)}</dd>`:''}<dt>有效期</dt><dd>${Number(a.days)||180} 天</dd></dl>`;}
async function bind(h){
 const {api,esc,formAction,UserError}=h;const active=h.active||(()=>true);let selected='';let rows=[],tasks=[];
 const form=document.querySelector('#memory-editor');const drafts=h.drafts||root.CampusNavigation?.forms(document,{selector:'#memory-editor'});drafts?.restore();if(!h.drafts)root.CampusNavigation?.register({active,dirty:()=>drafts?.dirty()||false});
 const reset=()=>{form.reset();form.elements.id.value='';form.elements.version.value='';drafts?.saved('#memory-editor');};
 const notice=()=>{document.querySelector('#agent-context-note').innerHTML=selected?`正在继续之前的讨论。<button id="agent-context-clear" type="button">开始新问题</button>`:'';const b=document.querySelector('#agent-context-clear');if(b)b.onclick=()=>{selected='';notice();};};
 async function refresh(){
 const [memory,discussion]=await Promise.allSettled([api('/api/agent/memories'),api('/api/agent/tasks')]);if(!active())return;if(memory.status==='fulfilled')rows=memory.value;if(discussion.status==='fulfilled')tasks=discussion.value;
 document.querySelector('#memory-list').innerHTML=memory.status==='rejected'?'<p class="meta">记忆暂时无法读取。<button type="button" data-agent-workspace-refresh>重新读取</button></p>':rows.length?rows.map(v=>`<article class="agent-memory-row"><b>${esc(kinds[v.kind]||'记忆')}</b><p class="preserve-lines">${esc(v.content)}</p>${v.scope?`<p class="meta">范围：${esc(v.scope)}</p>`:''}<p class="meta">有效至 ${esc(new Date(v.expires_at).toLocaleDateString('zh-CN'))}</p><div class="actions"><button type="button" data-memory-edit="${esc(v.id)}">修改</button><button type="button" data-memory-forget="${esc(v.id)}">遗忘</button></div></article>`).join(''):'<p class="meta">还没有记忆。你也可以在问答中输入“记住：……”，核对预览后确认。</p>';
 for(const b of document.querySelectorAll('[data-memory-edit]'))b.onclick=()=>{const v=rows.find(x=>x.id===b.dataset.memoryEdit);for(const k of ['id','version','kind','content','scope','days'])form.elements[k].value=v[k]??'';form.elements.content.focus();};
 for(const b of document.querySelectorAll('[data-memory-forget]'))b.onclick=async()=>{b.disabled=true;try{const v=rows.find(x=>x.id===b.dataset.memoryForget);await api('/api/agent/memories/'+encodeURIComponent(v.id),'DELETE',{version:v.version});selected='';reset();notice();await refresh();}catch(e){b.disabled=false;h.fail(e);}};
 document.querySelector('#agent-task-list').innerHTML=discussion.status==='rejected'?'<p class="meta">讨论记录暂时无法读取。<button type="button" data-agent-workspace-refresh>重新读取</button></p>':tasks.length?tasks.map(v=>`<article class="agent-memory-row"><p>${esc(v.goal)}</p><p class="meta">${esc(new Date(v.created_at).toLocaleString('zh-CN'))} · ${esc(root.CampusAgentHarness?.states[v.state]||'讨论记录')}</p><details><summary>查看上次摘要</summary><p class="preserve-lines">${esc(v.summary||'这次没有形成完整结论。')}</p></details><div class="actions"><button type="button" data-task-continue="${esc(v.id)}">继续这次讨论</button><button type="button" data-task-delete="${esc(v.id)}">删除摘要</button></div></article>`).join(''):'<p class="meta">完成一次问答后，讨论记录会出现在这里。</p>';
 for(const b of document.querySelectorAll('[data-task-continue]'))b.onclick=()=>{selected=b.dataset.taskContinue;notice();document.querySelector('#ask').elements.message.focus();};
 for(const b of document.querySelectorAll('[data-agent-workspace-refresh]'))b.onclick=()=>refresh().catch(h.fail);
 for(const b of document.querySelectorAll('[data-task-delete]'))b.onclick=async()=>{b.disabled=true;try{await api('/api/agent/tasks/'+encodeURIComponent(b.dataset.taskDelete),'DELETE');if(selected===b.dataset.taskDelete){selected='';notice();}await refresh();}catch(e){b.disabled=false;h.fail(e);}};
 }
 document.querySelector('#memory-reset').onclick=reset;
 formAction('#memory-editor',async data=>{const content=String(data.get('content')||'');if(new TextEncoder().encode(content).length>2000)throw new UserError('记忆内容过长，请控制在约 650 个汉字内。');if(new TextEncoder().encode(String(data.get('scope')||'')).length>200)throw new UserError('适用范围过长，请控制在约 65 个汉字内。');const body={kind:data.get('kind'),content,scope:data.get('scope'),days:Number(data.get('days'))};if(data.get('id')){body.id=data.get('id');body.version=Number(data.get('version'));}const point=drafts?.savepoint('#memory-editor');await api('/api/agent/memories','POST',body);if(!active())return;drafts?.saved('#memory-editor',point);reset();await refresh().catch(()=>h.fail(new UserError('记忆已保存，但列表暂时无法刷新。可重新打开此页查看。')));});
 await refresh().catch(()=>{if(active()){document.querySelector('#memory-list').innerHTML='<p class="meta">记忆与讨论记录暂时无法读取，重新打开可重试；仍可查询当前求职记录。</p>';}});return {taskID:()=>selected,refresh};
}
root.CampusAgentWorkspace={markup,bind,kinds,preview};if(typeof module!=='undefined')module.exports=root.CampusAgentWorkspace;
})(typeof window!=='undefined'?window:globalThis);
