(function(root){
'use strict';
const states={PENDING:'等待执行',RUNNING:'正在执行',PAUSED:'等待继续',COMPLETED:'已完成',CANCELLED:'已取消',STALE:'资料已变化',FAILED:'需重新发起'};
const taskNames={'company-choice':'同公司岗位取舍','interview-prep':'岗位面试准备','review-plan':'复盘与复习','daily-review':'今天的求职待办'};
const taskHints={'company-choice':'哪一份岗位更值得投','interview-prep':'围绕岗位整理准备依据','review-plan':'从复盘找到复习重点','daily-review':'看看变化、截止和投递记录'};
function markup({composer='',workspace=''}={}){return `<div class="agent-layout"><div class="agent-main">${composer}<section class="agent-panel agent-skills" aria-labelledby="agent-skills-title"><div class="agent-section-head"><h2 id="agent-skills-title">也可以直接做这些事</h2><span class="meta">使用已有记录</span></div><div id="agent-task-picker" class="agent-task-picker" aria-label="选择常用任务"></div><form id="agent-skill-form" novalidate><select name="skill_id" id="agent-skill-select" hidden aria-label="常用任务"></select><label id="agent-skill-input-label"><span id="agent-skill-field-name">输入</span><input name="value" maxlength="500" aria-describedby="agent-skill-description"></label><div id="agent-target-picker" hidden></div><div class="agent-task-submit"><p id="agent-skill-description" class="meta"></p><button class="btn btn-primary" type="submit">开始任务</button></div></form><div id="agent-execution-current" aria-live="polite"></div></section><details class="agent-history agent-panel"><summary>任务记录 <span id="agent-history-count" class="meta"></span></summary><p class="meta">最近 20 项任务。中断后可继续未完成的步骤。</p><div id="agent-execution-list"></div><button id="agent-history-refresh" type="button" class="text-btn">刷新记录</button></details></div><aside class="agent-side" aria-label="招聘提醒与助手设置"><section class="agent-panel agent-feed"><div class="agent-section-head"><h2>招聘变化</h2><span id="agent-todo-count" class="agent-count"></span></div><p class="meta">从岗位和资料的变化中，找到下一步。</p><button id="agent-feed-toggle" type="button" class="btn btn-small"></button><div id="agent-todo-list"></div><button id="agent-todo-more" type="button" class="text-btn" hidden>查看更多提醒</button><p id="agent-feed-more" class="meta" hidden>当前显示最新 50 项。处理后可继续查看较早的提醒。</p></section><details class="agent-panel agent-settings"><summary>问答设置</summary><div class="agent-setting-fields"><label>复杂问题使用<select id="agent-complex-model"><option value="">沿用当前模型</option></select></label><label>单次 token 预算<input id="agent-token-budget" type="number" min="1024" max="200000" value="48000"></label><label class="check"><input id="agent-local-lookup" type="checkbox" checked>简单记录查询在本地完成</label><p class="meta">启用学习检索模型时，复习和准备任务也可调用检索服务。问答预算按保守估算限制后续请求。模型报告的实际用量会显示在结果中。</p></div></details>${workspace}<details class="agent-panel agent-settings"><summary>外部学习资料</summary><p class="meta">连接公共 HTTPS MCP 服务，只读取你选定的文本资料。</p><form id="agent-connector-form" novalidate><label>资料来源名称<input name="name" required maxlength="120" placeholder="例如：我的复习手册"></label><label>MCP 服务地址<input name="url" type="url" required placeholder="https://你的域名/mcp"></label><label>访问令牌（需要时填写）<input name="token" type="password" maxlength="2048" autocomplete="off"></label><p class="meta">令牌仅保存在当前账号的这个浏览器中。</p><button type="button" id="agent-connector-discover" class="btn">读取可选资料</button><div id="agent-connector-resources"></div><button class="btn btn-primary" type="submit">保存资料范围</button></form><div id="agent-connector-list"></div></details></aside></div>`;}
function cleanCredentials(value){const out={};if(!value||typeof value!=='object'||Array.isArray(value))return out;for(const [id,token] of Object.entries(value)){if(/^[a-f0-9]{32}$/.test(id)&&typeof token==='string'&&token.length<=2048&&!/[\r\n\0]/.test(token))out[id]=token;}return out;}
function requestInput(skill,value,key){const v={skill_id:skill.id,request_key:key};if(skill.input==='company')v.company=value.trim();if(skill.input==='job_id')v.job_id=value.trim();if(skill.input==='topic')v.topic=value.trim();return v;}
function inputError(skill,value){const v=value.trim();if(skill.input==='job_id'&&!/^[a-f0-9]{32}$/.test(v))return '请搜索并选择一个要准备的岗位。';if(skill.input==='company'&&(!v||new TextEncoder().encode(v).length>200))return '请填写公司名称，控制在约 65 个汉字内。';if(skill.input==='topic'&&(!v||new TextEncoder().encode(v).length>500))return '请填写复习主题，控制在约 160 个汉字内。';return '';}
function canResume(v){if(typeof v.can_resume==='boolean')return v.can_resume;return ['PENDING','PAUSED'].includes(v.state)&&Number(v.resumes||0)<5;}
function usageText(result){const calls=Number(result.provider_calls)||0,b=result.budget;if(!calls||!b)return '';const total=(Number(b.prompt_tokens)||0)+(Number(b.completion_tokens)||0);if(b.unreported_calls>=calls)return '模型未报告 token 用量';return '已报告 '+total+' token'+(b.unreported_calls?'（部分请求未报告用量）':'');}
function taskTarget(v){const job=(v.grounded_observations||[]).find(o=>o.tool==='get_preparation_context')?.data?.job;if(job?.title)return (job.company||'')+' · '+job.title;const plan=v.plan||[];const name=v.skill_id==='company-choice'?'compare_company_jobs':v.skill_id==='review-plan'?'search_knowledge':v.skill_id==='interview-prep'?'get_preparation_context':'';const c=plan.find(x=>x.name===name);return c?.arguments?.company||c?.arguments?.query||(c?.arguments?.job_id?'岗位 '+c.arguments.job_id.slice(0,8):'');}
function renderExecution(v,esc,D,{compact=false}={}){const warnings=(v.failures||[]).map(f=>`<li>${esc(D?.label('tool',f.tool)||f.tool||'查询')}：${esc(f.next_step)}</li>`).join('');return `<article class="agent-execution${compact?' is-compact':''}"><div class="agent-execution-head"><div><h3>${esc(taskNames[v.skill_id]||'常用任务')}${taskTarget(v)?`<span>${esc(taskTarget(v))}</span>`:''}</h3><p class="meta">${esc(new Date(v.created_at).toLocaleString('zh-CN'))} · ${Number(v.next_step)||0}/${(v.plan||[]).length} 步</p></div><span class="agent-state is-${esc(v.state.toLowerCase())}">${esc(states[v.state]||v.state)}</span></div>${!compact&&v.answer?`<p class="agent-execution-answer preserve-lines">${esc(v.answer)}</p>`:''}${warnings&&v.state!=='COMPLETED'?`<div class="callout"><ul>${warnings}</ul></div>`:''}<details data-execution-details="${esc(v.id)}"><summary>${compact?'查看结果与依据':'核对完整结果与资料依据'}</summary><div data-execution-content><p class="meta">展开后读取完整记录。</p></div></details>${!compact?root.CampusAgentActions?.markup(v.next_actions,esc)||'':''}${warnings&&v.state==='COMPLETED'?`<details class="agent-recovered"><summary>曾遇到的问题（已恢复）</summary><ul>${warnings}</ul></details>`:''}<div class="actions">${['STALE','FAILED','CANCELLED'].includes(v.state)?`<button type="button" class="btn btn-small" data-execution-restart="${esc(v.id)}">用当前资料重新开始</button>`:''}${canResume(v)?`<button type="button" class="btn btn-small" data-execution-resume="${esc(v.id)}">继续未完成的步骤</button>`:''}${['PAUSED','PENDING','RUNNING'].includes(v.state)?`<button type="button" class="text-btn" data-execution-cancel="${esc(v.id)}">取消任务</button>`:''}</div></article>`;}
// A failed optional panel must not disable the question form or other panels.
async function loadPanels(panels){return Promise.allSettled(panels.map(async p=>{try{return await p.load();}catch(e){p.failed(e);throw e;}}));}
async function bind(h){
 const {api,esc,formAction,UserError,D}=h,active=h.active||(()=>true),models=root.CampusModels;
 let targetPicker,selectTask;let skills=[],feed={enabled:false,items:[]},connectors=[],resources=[],discovered='',nonce='',signature='',todoLimit=4,currentID='',currentState='',executionTimer,executionRevision=0;
 const $=s=>document.querySelector(s),user=h.user,key='campustrace:mcp-credentials:v1:'+user;
 let credentials={};try{credentials=cleanCredentials(JSON.parse(root.localStorage?.getItem(key)||'{}'));}catch{}
 function persistCredentials(){try{root.localStorage?.setItem(key,JSON.stringify(credentials));}catch{throw new UserError('无法保存本机访问令牌，请检查浏览器存储设置。');}}
 const drafts=h.drafts||root.CampusNavigation?.forms(document,{selector:'#agent-connector-form, #agent-skill-form',ignoreNames:['skill_id']});if(!h.drafts)root.CampusNavigation?.register({active,dirty:()=>drafts?.dirty()||false});
 function identity(){return {mask_name:root.CampusMatching?.matchIdentity()?.mask_name||'',model_config:models?.requestConfig(),retrieval:root.CampusKnowledge?.requestOptions()};}
 function panelFailure(selector,message,retry){if(!active())return;const node=$(selector);node.innerHTML=`<p class="meta" role="status">${esc(message)}</p><button type="button" class="text-btn">重新读取</button>`;node.querySelector('button').onclick=()=>retry().catch(()=>panelFailure(selector,message,retry));}
 function executionContents(v,includeActions=true){return `${includeActions?root.CampusAgentActions?.markup(v.next_actions,esc)||'':''}<p class="preserve-lines">${esc(v.answer||'任务还没有形成结论。')}</p><ol class="agent-step-list">${(v.plan||[]).map((c,i)=>`<li>${i<Number(v.next_step)?'已完成':'未完成'}：${esc(D?.label('tool',c.name)||c.name)}</li>`).join('')}</ol>${(v.grounded_observations||[]).map(o=>`<details class="agent-evidence"><summary>${esc(D?.label('tool',o.tool)||o.tool)}</summary>${h.renderData?h.renderData(o.data):`<pre>${esc(JSON.stringify(o.data,null,2))}</pre>`}</details>`).join('')}<details class="agent-diagnostics"><summary>原始记录（排查问题时使用）</summary><pre>${esc(JSON.stringify(v.grounded_observations||[],null,2))}</pre></details>`;}
 async function executions(){const revision=++executionRevision,rows=await api('/api/agent/executions');if(!active()||revision!==executionRevision)return;let current=rows.find(v=>v.id===currentID)||rows.find(v=>canResume(v)||v.state==='RUNNING');if(current){try{current=await api('/api/agent/executions/'+encodeURIComponent(current.id));}catch{/* Summary and controls remain available if the full result is temporarily unavailable. */}if(!active()||revision!==executionRevision)return;}currentState=current?.state||'';$('#agent-execution-current').innerHTML=current?renderExecution(current,esc,D):'';root.CampusAgentActions?.bind($('#agent-execution-current'),current?.next_actions,{navigate:h.navigate,fail:h.fail,active});$('#agent-history-count').textContent=rows.length?'最近 '+rows.length+' 项':'';$('#agent-execution-list').innerHTML=rows.filter(v=>v.id!==current?.id).map(v=>renderExecution(v,esc,D,{compact:true})).join('')||'<p class="meta">完成任务后，可在这里回看结果与依据。</p>';
  for(const panel of document.querySelectorAll('[data-execution-details]'))panel.ontoggle=async()=>{if(!panel.open||panel.dataset.loaded)return;panel.dataset.loaded='1';try{const v=await api('/api/agent/executions/'+encodeURIComponent(panel.dataset.executionDetails));if(active()){const content=panel.querySelector('[data-execution-content]');content.innerHTML=executionContents(v,!panel.closest('.agent-execution')?.querySelector('.agent-next'));root.CampusAgentActions?.bind(content,v.next_actions,{navigate:h.navigate,fail:h.fail,active});}}catch(e){delete panel.dataset.loaded;panel.querySelector('[data-execution-content]').innerHTML='<p class="meta">完整结果暂时无法读取，收起后重新展开可重试。</p>';}};
  for(const b of document.querySelectorAll('[data-execution-resume]'))b.onclick=async()=>{b.disabled=true;try{currentID=b.dataset.executionResume;await api('/api/agent/executions/'+encodeURIComponent(currentID)+'/resume','POST',identity());await executions();}catch(e){h.fail(e);await executions().catch(()=>{});if(b.isConnected)b.disabled=false;}};
  for(const b of document.querySelectorAll('[data-execution-restart]'))b.onclick=async()=>{b.disabled=true;try{const v=await api('/api/agent/executions/'+encodeURIComponent(b.dataset.executionRestart));if(!active())return;const next=root.CampusAgentActions?.restartInput(v);if(!next)throw new UserError('原任务的输入已清除或无法复用，请重新选择任务范围。');if(!selectTask)throw new UserError('常用任务列表暂时无法读取，请先重新读取任务列表。');if(drafts?.dirty()&&!await root.CampusNavigation.confirmDiscard())return;nonce='';signature='';selectTask?.(next);$('#agent-skill-form').scrollIntoView({behavior:'auto',block:'center'});$('#agent-skill-description').textContent='已填入原来的范围，将使用当前资料创建新任务。请核对后点击开始任务。';}catch(e){h.fail(e);}finally{if(b.isConnected)b.disabled=false;}};
  for(const b of document.querySelectorAll('[data-execution-cancel]'))b.onclick=async()=>{b.disabled=true;try{await api('/api/agent/executions/'+encodeURIComponent(b.dataset.executionCancel)+'/cancel','POST',{});await executions();}catch(e){if(b.isConnected)b.disabled=false;h.fail(e);}};
  root.clearTimeout(executionTimer);if(rows.some(v=>v.state==='RUNNING'))executionTimer=root.setTimeout(()=>{if(active())executions().catch(()=>{});},10000);
 }
 function renderTodos(){if(!active())return;$('#agent-feed-toggle').textContent=feed.enabled?'暂停提醒':'开启变化提醒';$('#agent-todo-count').textContent=feed.items.length?feed.items.length+(feed.more?'+':''):'';$('#agent-todo-list').innerHTML=feed.items.length?feed.items.slice(0,todoLimit).map(v=>`<article class="agent-todo"><p class="meta">${esc(v.company||'资料更新')}</p><h3>${esc(v.title)}</h3><p>${esc(v.explanation)}</p><div class="actions">${v.job_id?`<button type="button" class="text-btn" data-todo-job="${esc(v.job_id)}">查看岗位</button>`:''}<button type="button" class="text-btn" data-todo-dismiss="${esc(v.id)}">已处理</button></div></article>`).join(''):`<div class="agent-empty"><p>${feed.enabled?'还没有新的招聘变化':'提醒还未开启'}</p><span>${feed.enabled?'岗位原文或求职资料变化后，会在这里提醒你。':'开启后记录后续变化，你来决定是否分析和投递。'}</span></div>`;$('#agent-todo-more').hidden=feed.items.length<=4;$('#agent-todo-more').textContent=todoLimit>=feed.items.length?'收起提醒':'查看更多提醒';$('#agent-feed-more').hidden=!feed.more||todoLimit<feed.items.length;
  for(const b of document.querySelectorAll('[data-todo-job]'))b.onclick=()=>h.navigate('matching',{jobID:b.dataset.todoJob}).catch(h.fail);
  for(const b of document.querySelectorAll('[data-todo-dismiss]'))b.onclick=async()=>{b.disabled=true;try{await api('/api/agent/todos/'+encodeURIComponent(b.dataset.todoDismiss)+'/dismiss','POST',{});await todos();}catch(e){if(b.isConnected)b.disabled=false;h.fail(e);}};
 }
 async function todos(){feed=await api('/api/agent/todos');renderTodos();}
 $('#agent-todo-more').onclick=()=>{todoLimit=todoLimit>=feed.items.length?4:todoLimit+6;renderTodos();};
 async function connectionList(){connectors=await api('/api/agent/connectors');if(!active())return;$('#agent-connector-list').innerHTML=connectors.map(v=>`<article class="agent-connection"><strong>${esc(v.name)}</strong><p class="meta">已授权 ${(v.allowed_resources||[]).length} 份资料</p><label>更新本机令牌<input type="password" data-connector-token="${esc(v.id)}" maxlength="2048" autocomplete="off" placeholder="${credentials[v.id]?'已保存；留空保存会清除令牌':'无需令牌时留空'}"></label><div class="actions"><button type="button" class="text-btn" data-connector-token-save="${esc(v.id)}">保存本机令牌</button><button type="button" class="text-btn" data-connector-remove="${esc(v.id)}">移除连接</button></div><p class="meta" data-connector-status="${esc(v.id)}" role="status"></p></article>`).join('');
  for(const b of document.querySelectorAll('[data-connector-token-save]'))b.onclick=()=>{const id=b.dataset.connectorTokenSave,input=$('[data-connector-token="'+id+'"]');try{const token=input.value;if(/[\r\n\0]/.test(token)||token.length>2048)throw new UserError('访问令牌格式无效。');if(token)credentials[id]=token;else delete credentials[id];persistCredentials();input.value='';$('[data-connector-status="'+id+'"]').textContent=token?'本机令牌已更新。':'本机令牌已清除。';}catch(e){h.fail(e);}};
  for(const b of document.querySelectorAll('[data-connector-remove]'))b.onclick=async()=>{b.disabled=true;try{await api('/api/agent/connectors/'+encodeURIComponent(b.dataset.connectorRemove),'DELETE');delete credentials[b.dataset.connectorRemove];try{persistCredentials();}catch{h.fail(new UserError('连接已移除，本机令牌清理未能保存。'));}await connectionList();}catch(e){if(b.isConnected)b.disabled=false;h.fail(e);}};
 }
 async function loadSkills(){
  skills=await api('/api/agent/skills');if(!active())return;const select=$('#agent-skill-select'),form=$('#agent-skill-form'),input=form.elements.value;
  select.innerHTML=skills.map(v=>`<option value="${esc(v.id)}">${esc(v.name)}</option>`).join('');select.value='daily-review';drafts?.restore();
  $('#agent-task-picker').innerHTML=skills.map(v=>`<button type="button" data-agent-task="${esc(v.id)}" aria-pressed="false"><strong>${esc(v.name)}</strong><span>${esc(taskHints[v.id]||v.description)}</span></button>`).join('');
  targetPicker=root.CampusAgentActions.bindTargets(form,{api,active});const values={};let previous=select.value;
  const change=()=>{const skill=skills.find(v=>v.id===select.value);if(!skill)return;if(previous!==skill.id){values[previous]=input.value;input.value=values[skill.id]||'';previous=skill.id;}
   $('#agent-skill-input-label').hidden=['none','job_id'].includes(skill.input);input.required=skill.input!=='none';input.maxLength=skill.input==='job_id'?32:skill.input==='company'?200:500;
   input.placeholder={company:'输入或选择公司名称',topic:'例如：Go 并发与消息重试'}[skill.input]||'';$('#agent-skill-field-name').textContent={company:'要比较的公司',topic:'这次想复习什么'}[skill.input]||'输入';$('#agent-skill-description').textContent=skill.description;
   for(const b of document.querySelectorAll('[data-agent-task]'))b.setAttribute('aria-pressed',String(b.dataset.agentTask===skill.id));targetPicker.activate(skill.input);
  };
  selectTask=next=>{const skill=skills.find(v=>v.id===next.id);if(!skill||inputError(skill,next.value||''))return;select.value=skill.id;values[skill.id]=next.value||'';if(previous===skill.id)input.value=values[skill.id];change();input.dispatchEvent(new Event('input',{bubbles:true}));};
  select.onchange=change;for(const b of document.querySelectorAll('[data-agent-task]'))b.onclick=()=>{select.value=b.dataset.agentTask;change();};change();if(h.initialSkill)selectTask(h.initialSkill);drafts?.saved('#agent-skill-form');form.querySelector('button[type="submit"]').disabled=false;
 }
 formAction('#agent-skill-form',async data=>{const skill=skills.find(v=>v.id===data.get('skill_id'));if(!skill)throw new UserError('任务列表暂时无法读取，请重新读取后再开始。');const value=String(data.get('value')||''),error=inputError(skill,value);if(error)throw new UserError(error);const next=JSON.stringify([skill.id,value]);if(next!==signature||!nonce){nonce=root.crypto.randomUUID();signature=next;}const body=requestInput(skill,value,nonce);const point=drafts?.savepoint('#agent-skill-form');const button=$('#agent-skill-form button[type="submit"]');button.textContent='正在整理记录…';let v;try{v=await api('/api/agent/executions','POST',{...body,...identity()});}catch(e){if(active())await executions().catch(()=>{});throw e;}finally{button.textContent='开始任务';}if(!active())return;currentID=v.id;nonce='';$('#agent-result')?.replaceChildren();drafts?.saved('#agent-skill-form',point);$('#agent-execution-current').innerHTML=renderExecution(v,esc,D);await executions().catch(()=>h.fail(new UserError('任务已保存，但列表暂时无法刷新。刷新记录可查看。')));});
 const complex=$('#agent-complex-model');for(const v of models?.configuredChoices?.()||[]){const option=document.createElement('option');option.value=v.id;option.textContent=v.name;complex.append(option);}
 $('#agent-feed-toggle').onclick=async function(){this.disabled=true;try{await api('/api/agent/todos/settings','POST',{enabled:!feed.enabled});await todos();}catch(e){h.fail(e);}finally{this.disabled=false;}};
 $('#agent-history-refresh').onclick=()=>executions().catch(()=>panelFailure('#agent-execution-list','任务记录暂时无法读取。',executions));
 const form=$('#agent-connector-form');$('#agent-connector-discover').onclick=async function(){this.disabled=true;try{if(!form.reportValidity())return;const body={name:form.elements.name.value,url:form.elements.url.value,token:form.elements.token.value,allowed_resources:[]};const catalog=await api('/api/agent/connectors/discover','POST',body);if(!active())return;resources=catalog.filter(v=>!v.mime_type||v.mime_type.toLowerCase().startsWith('text/'));discovered=JSON.stringify([body.url,body.token]);$('#agent-connector-resources').innerHTML=resources.length?resources.map((v,i)=>`<label class="check"><input type="checkbox" data-resource-index="${i}">${esc(v.name||v.uri)}</label>`).join(''):'<p class="meta">这项服务没有提供可选择的文本资料。</p>';}catch(e){h.fail(e);}finally{this.disabled=false;}};
 formAction('#agent-connector-form',async data=>{if(discovered!==JSON.stringify([data.get('url'),data.get('token')]))throw new UserError('地址或令牌已变化，请重新读取可选资料。');const allowed=[...document.querySelectorAll('[data-resource-index]:checked')].map(x=>resources[Number(x.dataset.resourceIndex)].uri);if(!allowed.length)throw new UserError('请至少选择一份允许助手读取的资料。');const token=String(data.get('token')||''),v=await api('/api/agent/connectors','POST',{name:data.get('name'),url:data.get('url'),token,allowed_resources:allowed});if(!active())return;form.reset();drafts?.saved('#agent-connector-form');$('#agent-connector-resources').replaceChildren();resources=[];discovered='';if(token){credentials[v.id]=token;try{persistCredentials();}catch{h.fail(new UserError('连接已保存，但令牌未能保存在浏览器。当前页面仍可读取，重新打开后需更新本机令牌。'));}}await connectionList().catch(()=>h.fail(new UserError('连接已保存，列表暂时无法刷新，请重新打开此页。')));});
 async function refresh(){return loadPanels([{load:executions,failed:()=>panelFailure('#agent-execution-list','任务记录暂时无法读取。',executions)},{load:todos,failed:()=>panelFailure('#agent-todo-list','招聘提醒暂时无法读取。',todos)}]);}
 await loadPanels([{load:loadSkills,failed:()=>{if(active()){$('#agent-skill-form button[type="submit"]').disabled=true;panelFailure('#agent-task-picker','常用任务暂时无法读取。',loadSkills);}}},{load:refresh,failed:()=>{}},{load:connectionList,failed:()=>panelFailure('#agent-connector-list','资料连接暂时无法读取。',connectionList)}]);
 return {showQuestion(){if(['COMPLETED','FAILED','STALE','CANCELLED'].includes(currentState))currentID='';},options(){const budget=Number($('#agent-token-budget').value);if(!Number.isInteger(budget)||budget<1024||budget>200000)throw new UserError('问答预算应为 1024—200000 的整数。');return {local_lookup:$('#agent-local-lookup').checked,token_budget:budget,complex_model_config:models?.requestConfigFor?.(complex.value),mcp_credentials:Object.fromEntries(connectors.filter(v=>credentials[v.id]).map(v=>[v.id,credentials[v.id]]))};},refresh};
}
root.CampusAgentHarness={markup,bind,requestInput,renderExecution,states,cleanCredentials,inputError,canResume,loadPanels,usageText};if(typeof module!=='undefined')module.exports=root.CampusAgentHarness;
})(typeof window!=='undefined'?window:globalThis);
