(function(root){
'use strict';
const defaults={embedding:{url:'https://api.siliconflow.cn/v1/embeddings',model:'BAAI/bge-m3'},rerank:{url:'https://api.siliconflow.cn/v1/rerank',model:'BAAI/bge-reranker-v2-m3'}};
let user='',config={};
const browsing=new Map();
function browseSignature(){const v=requestOptions();return JSON.stringify([v.embedding?.url,v.embedding?.model,v.rerank?.url,v.rerank?.model,v.mask_name]);}
const key=id=>'campustrace:retrieval:v1:'+id;
function validEndpoint(v){try{const u=new URL(v);return u.protocol==='https:'&&!u.username&&!u.password&&!u.search&&!u.hash&&(!u.port||u.port==='443')&&u.hostname.includes('.')&&!/^\d+\.\d+\.\d+\.\d+$/.test(u.hostname)&&!u.hostname.includes(':')&&!/\.(local|internal|localhost)$/.test(u.hostname)&&u.pathname!=='/';}catch{return false;}}
function clean(value){
 const out={};if(!value||typeof value!=='object'||Array.isArray(value))return out;
 for(const name of ['embedding','rerank']){const v=value[name];if(v&&typeof v.api_key==='string'&&v.api_key.trim()&&v.api_key.length<=1024&&!/[\r\n\0]/.test(v.api_key)&&typeof v.model==='string'&&v.model.trim()&&v.model.length<=128&&!/[\r\n\0]/.test(v.model)&&typeof v.url==='string'&&v.url.length<=2048&&validEndpoint(v.url))out[name]={url:v.url,model:v.model,api_key:v.api_key};}
 out.enabled=value.enabled===true&&!!out.embedding;out.rerankEnabled=value.rerankEnabled===true&&!!out.rerank;return out;
}
function bindUser(id){id=String(id||'');if(!/^[a-zA-Z0-9_-]{1,128}$/.test(id))throw new Error('请先登录，再配置学习资料检索。');if(id===user)return;user=id;config={};try{config=clean(JSON.parse(root.localStorage?.getItem(key(user))||'{}'));}catch{}}
function lock(){user='';config={};browsing.clear();root.CampusKnowledgeBulk?.lock();}
function save(value){if(!user)throw new Error('请先登录。');if(root.location&&root.location.protocol!=='https:'&&!['localhost','127.0.0.1','[::1]'].includes(root.location.hostname))throw new Error('请使用本机地址或 HTTPS 页面保存密钥。');const next=clean(value);if(value.enabled&&!next.embedding)throw new Error('请填写有效的语义检索密钥与模型设置。');if(value.rerankEnabled&&!next.rerank)throw new Error('请填写有效的重排序密钥与模型设置。');try{root.localStorage.setItem(key(user),JSON.stringify(next));}catch{throw new Error('无法保存本机检索设置，请检查浏览器存储。');}config=next;}
function requestOptions(){return {embedding:config.enabled?config.embedding:undefined,rerank:config.rerankEnabled?config.rerank:undefined,mask_name:root.CampusMatching?.matchIdentity()?.mask_name||''};}
function indexOptions(){return {embedding:config.embedding,mask_name:root.CampusMatching?.matchIdentity()?.mask_name||''};}
const notices={RETRIEVAL_INPUT_CHANGED:'材料、模型或预览已变化，请重新预览外发文字；未保存旧索引。',RETRIEVAL_INDEX_REQUIRED:'还没有此模型的语义索引，当前使用关键词检索。',RETRIEVAL_INDEX_PARTIAL:'部分材料还未建立语义索引；其余材料仍参加关键词检索。',RETRIEVAL_DIMENSION_CHANGED:'模型返回的向量维度变了；请清除旧索引后重新建立。',RETRIEVAL_AUTH_FAILED:'检索服务拒绝了密钥，请核对服务商与密钥。',RETRIEVAL_BALANCE_LOW:'检索服务余额不足。',RETRIEVAL_RATE_LIMIT:'检索服务请求较多，请稍后再试。',RETRIEVAL_TIMEOUT:'检索模型响应超时，本次保留已有检索结果。',RETRIEVAL_CONNECTION_FAILED:'无法连接检索服务，请核对地址和设备网络。',RETRIEVAL_RESPONSE_INVALID:'检索模型返回的向量或排名格式无效。',RETRIEVAL_PROVIDER_FAILED:'检索服务暂不可用，本次保留已有检索结果。',RETRIEVAL_UNAVAILABLE:'检索模型暂不可用。',RETRIEVAL_CACHE_CAPACITY:'语义索引缓存已满，请清除旧索引后重新建立。'};
const modeLabels={keyword:'关键词检索',hybrid:'关键词＋语义检索','keyword+rerank':'关键词检索＋重排序','hybrid+rerank':'关键词＋语义检索＋重排序'};
function settingsMarkup(esc){return `<section class="settings-panel knowledge-settings" id="knowledge-model-settings"><div class="settings-body"><h3>学习资料检索</h3><p class="form-note">与简历分析模型分开配置。默认提供硅基流动预设，也可使用兼容的公共 HTTPS 接口。保存不会发送材料。</p><form id="knowledge-settings-form" novalidate><label class="check"><input name="enabled" type="checkbox" ${config.enabled?'checked':''}>在搜索和求职问答中启用语义检索</label><label>硅基流动 API 密钥<input name="key" type="password" maxlength="1024" autocomplete="off" placeholder="${config.embedding?'已保存，留空沿用':'粘贴检索服务的密钥'}"></label><label class="check"><input name="rerankEnabled" type="checkbox" ${config.rerankEnabled?'checked':''}>对最多 20 个候选片段启用重排序（可选）</label><details><summary>自定义接口与模型</summary><div class="form-grid"><label>语义检索接口<input name="embedding_url" type="url" value="${esc(config.embedding?.url||defaults.embedding.url)}" required maxlength="2048"></label><label>语义检索模型<input name="embedding_model" value="${esc(config.embedding?.model||defaults.embedding.model)}" required maxlength="128"></label><label>重排序接口<input name="rerank_url" type="url" value="${esc(config.rerank?.url||defaults.rerank.url)}" maxlength="2048"></label><label>重排序模型<input name="rerank_model" value="${esc(config.rerank?.model||defaults.rerank.model)}" maxlength="128"></label></div><label>独立重排序密钥（可选）<input name="rerank_key" type="password" maxlength="1024" autocomplete="off" placeholder="留空沿用同服务商密钥"></label></details><p class="form-note">密钥按账号保存在此浏览器。启用后，搜索会发送脱敏问题；重排序会额外发送候选材料。建立索引前可逐段预览外发文字。</p><div class="actions"><button type="submit" class="btn btn-primary">保存检索设置</button><button type="button" id="knowledge-key-remove" class="text-btn">删除本机检索设置</button></div></form><p id="knowledge-settings-notice" class="meta" aria-live="polite"></p></div></section>`;}
function fromForm(data){
 const enabled=data.get('enabled')==='on',rerankEnabled=data.get('rerankEnabled')==='on',inputKey=String(data.get('key')||'').trim();
 const embedding={url:String(data.get('embedding_url')||'').trim(),model:String(data.get('embedding_model')||'').trim(),api_key:inputKey||config.embedding?.api_key||''};
 if(!inputKey&&config.embedding&&(!validEndpoint(embedding.url)||new URL(config.embedding.url).origin!==new URL(embedding.url).origin))embedding.api_key='';
 let rerankKey=String(data.get('rerank_key')||'').trim();const url=String(data.get('rerank_url')||'').trim();
 if(!rerankKey&&config.rerank?.url===url)rerankKey=config.rerank.api_key;
 // A key must never be silently reused at a newly entered provider origin.
 if(!rerankKey&&validEndpoint(url)&&validEndpoint(embedding.url)&&new URL(url).origin===new URL(embedding.url).origin)rerankKey=embedding.api_key;

 return {enabled,rerankEnabled,embedding,rerank:{url,model:String(data.get('rerank_model')||'').trim(),api_key:rerankKey}};
}
function bindSettings({formAction,UserError,active=()=>true}){
 formAction('#knowledge-settings-form',async data=>{try{save(fromForm(data));}catch(e){throw new UserError(e.message);}if(!active())return;document.querySelector('#knowledge-settings-form').elements.key.value='';document.querySelector('#knowledge-settings-form').elements.rerank_key.value='';document.querySelector('#knowledge-settings-notice').textContent='已保存到此浏览器。已有材料请到「学习资料」预览并建立索引。';});
 document.querySelector('#knowledge-key-remove').onclick=()=>{try{save({});if(active()){document.querySelector('#knowledge-settings-form').reset();document.querySelector('#knowledge-settings-form').elements.enabled.checked=false;document.querySelector('#knowledge-settings-form').elements.rerankEnabled.checked=false;document.querySelector('#knowledge-settings-notice').textContent='已删除本机检索密钥与设置；本地材料仍可用关键词搜索。';}}catch(e){document.querySelector('#knowledge-settings-notice').textContent=e.message;}};
}
function resultMarkup(result,esc){const info=result.retrieval||{};return `<p class="meta">${esc(modeLabels[info.mode]||'关键词检索')} · ${Number(info.milliseconds)||0} ms${info.query_cache_hit?' · 已复用问题向量':''} · ${Number(info.candidates)||0} 个候选</p>${(info.warnings||[]).map(code=>`<p class="knowledge-warning">${esc(notices[code]||'本次使用可用的检索结果。')}</p>`).join('')}${(result.hits||[]).map((v,i)=>`<article class="knowledge-hit"><h3>${i+1}. ${esc(v.title)}</h3><p class="meta">材料 ${esc(v.document_id)} · 第 ${Number(v.index)+1} 段</p><pre>${esc(v.text)}</pre>${/^[a-f0-9]{32}$/.test(v.document_id||'')?`<button type="button" class="text-btn" data-knowledge-source="${esc(v.document_id)}">阅读完整材料</button>`:''}<details><summary>查看检索依据</summary><p class="meta">${v.keyword>0?'命中关键词。':''}${v.cosine>0?'语义相似度 '+Number(v.cosine).toFixed(3)+'。':''}${v.rerank_score!=null?'重排序相关性 '+Number(v.rerank_score).toFixed(3)+'。':''} 这些数值用于排列学习资料，不代表岗位匹配度。</p></details></article>`).join('')||'<p class="empty">暂无结果。可以换个问题，或先导入相关材料。</p>'}`;}
async function page(set,heading,h){
 const {api,esc,formAction,UserError,navigate}=h,active=h.active||(()=>true),$=s=>document.querySelector(s);
 const capabilities=await api('/api/profile/resume/capabilities');if(!active())return;bindUser(capabilities.user_id);root.CampusMatching?.bindUser(capabilities.user_id);
 const remembered=browsing.get(user)||{};
 if(!set(`${heading}<div class="knowledge-layout"><div><section class="agent-panel knowledge-source" id="knowledge-source" hidden aria-live="polite"></section><section class="agent-panel"><form id="knowledge-search" novalidate><label>想复习什么？<input name="query" required maxlength="1000" placeholder="例如：消费者挂了，已经取走的消息怎么办？"></label><div class="actions"><button class="btn btn-primary" type="submit">搜索学习资料</button><button id="knowledge-settings" class="text-btn" type="button">配置检索模型</button></div><p class="meta">${config.enabled?'已启用语义检索，问题会发给检索服务。':'当前使用本地关键词检索。'}${config.rerankEnabled?' 已启用重排序，候选材料会发给检索服务。':''}</p></form><div id="knowledge-results" aria-live="polite"></div></section><details class="agent-panel knowledge-import"><summary>添加学习材料</summary><form id="knowledge-import" novalidate><label>材料标题<input name="title" required maxlength="200" placeholder="例如：Redis 消费恢复笔记"></label><label>选择文本文件（可选）<input id="knowledge-file" type="file" accept=".txt,.md,text/plain,text/markdown"></label><label>材料正文<textarea name="text" required rows="9" maxlength="60000" placeholder="粘贴你自己的复习笔记"></textarea></label><p class="meta">最多 60,000 字节。保存到本地；建立语义索引时再核对外发文字。</p><button type="submit" class="btn btn-primary">保存材料到本地</button></form><p id="knowledge-import-notice" class="meta" aria-live="polite"></p></details>${root.CampusKnowledgeBulk?.markup()||''}<section class="agent-panel"><div class="agent-section-head"><h2>我的材料</h2><button class="text-btn" id="knowledge-refresh" type="button">刷新</button></div><div id="knowledge-documents"></div><div class="actions"><button class="btn btn-small" id="knowledge-prev" type="button">上一页</button><button class="btn btn-small" id="knowledge-next" type="button">下一页</button></div></section></div><aside><section class="agent-panel"><h2>语义索引</h2><p class="meta">已完成片段自动跳过；更换模型后需重新建立索引。</p><p id="knowledge-index-status" class="meta"></p><button id="knowledge-preview" class="btn" type="button">预览下一批外发文字</button><div id="knowledge-index-preview"></div><button id="knowledge-clear" class="text-btn" type="button">清除语义索引</button></section><details class="knowledge-help"><summary>学习资料使用说明</summary><p>索引建立后，求职问答与「复盘与复习」也会使用这些材料。关闭语义检索仍可用关键词搜索。</p><p>材料用于学习参考；岗位匹配继续读取完整求职资料和 JD。</p><p>重排序默认关闭，可先观察检索结果再启用。</p></details></aside></div>`))return;
 $('#knowledge-settings').onclick=()=>navigate('models');
 const drafts=root.CampusNavigation?.forms(document,{selector:'#knowledge-import'});drafts?.restore();
 let offset=remembered.offset||0,preview=null,sourceRevision=0,sourceID='',listRevision=0,result=null,searchQuery='',searchSignature='';
 $('#knowledge-search').elements.query.value=remembered.query||'';
 const checkpoint=()=>browsing.set(capabilities.user_id,{query:$('#knowledge-search').elements.query.value,offset,result,searchQuery,signature:searchSignature,sourceID,sourceScroll:$('#knowledge-source pre')?.scrollTop||0,scroll:root.scrollY||0});
 let bulk;root.CampusNavigation?.register({active,dirty:()=>drafts?.dirty()||false,checkpoint,dispose:()=>bulk?.dispose()});
 const showError=e=>{if(active())$('#notice').textContent=e instanceof UserError?e.message:'操作暂未完成，请刷新后重试。';};
 function closeSource(){++sourceRevision;sourceID='';if(active()){$('#knowledge-source').hidden=true;$('#knowledge-source').replaceChildren();}}
 async function openSource(id,restore=false){
  if(!/^[a-f0-9]{32}$/.test(id))return;const rev=++sourceRevision;sourceID=id;const box=$('#knowledge-source');box.hidden=false;box.innerHTML='<p class="meta">正在读取完整材料…</p>';
  try{const doc=await api('/api/documents/'+encodeURIComponent(id));if(!active()||rev!==sourceRevision)return;box.innerHTML=`<div class="agent-section-head"><h2 tabindex="-1">${esc(doc.title)}</h2><button type="button" class="text-btn" data-source-close>收起材料</button></div><pre>${esc(doc.text)}</pre>`;box.querySelector('h2').focus({preventScroll:true});}
  catch{if(!active()||rev!==sourceRevision)return;box.innerHTML='<h2>这份材料暂时无法读取</h2><p>材料可能已删除，或当前账号无法访问。可以刷新材料列表后重新选择。</p><button type="button" class="text-btn" data-source-close>收起提示</button>';}
  if(active()&&rev===sourceRevision){box.querySelector('[data-source-close]').onclick=closeSource;if(restore)box.querySelector('pre')&&(box.querySelector('pre').scrollTop=remembered.sourceScroll||0);else box.scrollIntoView({behavior:'auto',block:'start'});}
 }
 function bindSources(){for(const b of document.querySelectorAll('[data-knowledge-source]'))b.onclick=()=>openSource(b.dataset.knowledgeSource);}
 function invalidatePreview(){preview=null;if(active())$('#knowledge-index-preview').replaceChildren();}
 async function indexStatus(){if(!config.embedding){if(active()){$('#knowledge-index-status').textContent='尚未配置语义检索模型。';$('#knowledge-preview').disabled=true;}return;}const next=await api('/api/knowledge/index/preview','POST',{retrieval:indexOptions()});if(active())$('#knowledge-index-status').textContent=`已建立 ${next.indexed} / ${next.total} 段，待处理 ${next.pending} 段。`;}
 async function list(){const rev=++listRevision;const rows=await api('/api/documents?offset='+offset);if(!active()||rev!==listRevision)return;$('#knowledge-prev').disabled=offset===0;$('#knowledge-next').disabled=rows.length<=50;$('#knowledge-documents').innerHTML=rows.slice(0,50).map(v=>`<article class="knowledge-document"><div><h3>${esc(v.title)}</h3><p class="meta">${v.chunks} 个片段</p></div><div class="actions"><button class="text-btn" data-knowledge-open="${esc(v.id)}" type="button">查看</button><button class="text-btn" data-knowledge-delete="${esc(v.id)}" type="button">删除</button></div><div class="knowledge-document-body" data-knowledge-body="${esc(v.id)}"></div></article>`).join('')||'<p class="empty">还没有学习材料。先添加一份复习笔记吧。</p>';
  for(const b of document.querySelectorAll('[data-knowledge-open]'))b.onclick=()=>openSource(b.dataset.knowledgeOpen);
  for(const b of document.querySelectorAll('[data-knowledge-delete]'))b.onclick=()=>{const box=document.querySelector(`[data-knowledge-body="${b.dataset.knowledgeDelete}"]`);box.innerHTML='<p>删除这份材料及其索引？</p><button class="btn btn-small" type="button" data-confirm-delete>确认删除</button><button class="text-btn" type="button" data-cancel-delete>保留</button>';box.querySelector('[data-cancel-delete]').onclick=()=>box.replaceChildren();box.querySelector('[data-confirm-delete]').onclick=async function(){this.disabled=true;try{await api('/api/documents/'+encodeURIComponent(b.dataset.knowledgeDelete),'DELETE');if(!active())return;invalidatePreview();result=null;$('#knowledge-results').replaceChildren();if(sourceID===b.dataset.knowledgeDelete)closeSource();await list();await indexStatus();}catch(e){showError(e);if(this.isConnected)this.disabled=false;}};};
 }
 $('#knowledge-refresh').onclick=()=>list().then(indexStatus).catch(showError);$('#knowledge-prev').onclick=()=>{offset=Math.max(0,offset-50);list().catch(showError);};$('#knowledge-next').onclick=()=>{offset+=50;list().catch(showError);};
 $('#knowledge-file').onchange=async function(){const file=this.files?.[0];if(!file)return;if(file.size>60000){showError(new UserError('文本文件超过 60,000 字节，请先分成几份。'));return;}try{const text=await file.text();if(!active())return;$('#knowledge-import').elements.text.value=text;$('#knowledge-import').elements.text.dispatchEvent(new Event('input',{bubbles:true}));if(!$('#knowledge-import').elements.title.value){$('#knowledge-import').elements.title.value=file.name.replace(/\.(txt|md)$/i,'');$('#knowledge-import').elements.title.dispatchEvent(new Event('input',{bubbles:true}));}}catch{showError(new UserError('无法读取文本文件，请粘贴正文。'));}};
 formAction('#knowledge-search',async data=>{const query=String(data.get('query')||'').trim();if(new TextEncoder().encode(query).length>1000)throw new UserError('问题最多 1,000 字节，请缩短后重试。');const out=await api('/api/knowledge/search','POST',{query,k:5,retrieval:requestOptions()});if(active()){result=out;searchQuery=query;searchSignature=browseSignature();$('#knowledge-results').innerHTML=resultMarkup(out,esc);bindSources();}});
 formAction('#knowledge-import',async data=>{const body={title:String(data.get('title')||'').trim(),text:String(data.get('text')||'')};if(new TextEncoder().encode(body.title).length>200||new TextEncoder().encode(body.text).length>60000)throw new UserError('标题最多 200 字节，正文最多 60,000 字节；请缩短或拆成几份。');const point=drafts?.savepoint('#knowledge-import');await api('/api/documents','POST',body);if(!active())return;if($('#knowledge-import').elements.title.value.trim()===body.title&&$('#knowledge-import').elements.text.value===body.text){$('#knowledge-import').reset();drafts?.saved('#knowledge-import');}else{drafts?.saved('#knowledge-import',point);}$('#knowledge-import-notice').textContent='已保存到本地。需要语义搜索时，可预览并建立索引。';invalidatePreview();result=null;$('#knowledge-results').replaceChildren();offset=0;await list().then(indexStatus).catch(()=>showError(new UserError('材料已保存，但列表暂时无法刷新；请点刷新查看。')));});
 $('#knowledge-preview').onclick=async function(){this.disabled=true;try{const next=await api('/api/knowledge/index/preview','POST',{retrieval:indexOptions()});if(!active())return;preview=next;$('#knowledge-index-preview').innerHTML=next.inputs.length?`<p>本批 ${next.inputs.length} 段，发往 ${esc(next.url)}，使用 ${esc(next.model)}。</p><details open><summary>核对实际发送的脱敏文字</summary>${next.inputs.map(v=>`<article><h3>${esc(v.title)}</h3><pre>${esc(v.text)}</pre></article>`).join('')}</details><button class="btn btn-primary" id="knowledge-build" type="button">确认发送本批并建立索引</button>`:'<p>当前模型的索引已完成，没有待处理片段。</p>';$('#knowledge-build')?.addEventListener('click',async function(){this.disabled=true;try{const out=await api('/api/knowledge/index','POST',{retrieval:indexOptions(),key:preview.key,confirm:true});if(!active())return;invalidatePreview();$('#notice').textContent=`本批已建立 ${out.indexed} 段索引。`;await indexStatus();}catch(e){showError(e);invalidatePreview();await indexStatus().catch(()=>{});}});}catch(e){showError(e);}finally{if(this.isConnected)this.disabled=false;}};
 $('#knowledge-clear').onclick=function(){const b=this;if(b.dataset.confirm!=='yes'){b.dataset.confirm='yes';b.textContent='确认清除全部语义索引（材料保留）';return;}b.disabled=true;api('/api/knowledge/index','DELETE').then(async()=>{if(!active())return;invalidatePreview();await indexStatus();b.dataset.confirm='';b.textContent='清除语义索引';}).catch(showError).finally(()=>{if(b.isConnected)b.disabled=false;});};
 bulk=root.CampusKnowledgeBulk?.mount({user:capabilities.user_id,api,esc,active,onSaved:async()=>{invalidatePreview();result=null;$('#knowledge-results').replaceChildren();await list().then(indexStatus);}});
 async function restoreResults(){if(!remembered.result)return;try{const current=await api('/api/knowledge/state');if(!active())return;if(current.version===remembered.result.retrieval?.corpus_version&&remembered.signature===browseSignature()){result=remembered.result;searchQuery=remembered.searchQuery||'';searchSignature=remembered.signature;$('#knowledge-results').innerHTML=`<p class="meta">上次搜索：${esc(searchQuery)}</p>`+resultMarkup(result,esc);bindSources();}else $('#knowledge-results').innerHTML='<p class="meta">材料或检索设置已变化，请重新搜索。</p>';}catch{if(active())$('#knowledge-results').innerHTML='<p class="meta">暂时无法核对上次结果是否仍有效，请重新搜索。</p>';}}
 await Promise.allSettled([list().catch(showError),restoreResults(),(h.initialDocument||remembered.sourceID)?openSource(h.initialDocument||remembered.sourceID,!h.initialDocument):Promise.resolve(),indexStatus().catch(()=>{if(active())$('#knowledge-index-status').textContent='索引进度暂时无法读取，可点预览重试。';})]);
 if(active()&&!h.initialDocument&&Number.isFinite(remembered.scroll))root.requestAnimationFrame?.(()=>{if(active())root.scrollTo?.({top:remembered.scroll,behavior:'instant'});});
}
root.CampusKnowledge={defaults,bindUser,lock,save,clean,validEndpoint,requestOptions,indexOptions,settingsMarkup,bindSettings,resultMarkup,page,notices,fromForm};if(typeof module==='object'&&module.exports)module.exports=root.CampusKnowledge;
})(typeof window!=='undefined'?window:globalThis);
