'use strict';
const CampusMatchTasks=(function(root){
 const states={RUNNING:'正在分析',PAUSING:'完成当前批次后暂停',PAUSED:'已暂停',WAITING_AUTH:'需要重新核对后继续',COMPLETED:'本轮已完成',COMPLETED_WITH_ERRORS:'已完成，部分失败',CANCELLED:'已取消'};
 const active=v=>['RUNNING','PAUSING'].includes(v?.state);
 function progress(run,D){return {pending:(run.items||[]).filter(i=>['QUEUED','PAUSED','INTERRUPTED'].includes(i.state)).map(i=>i.job_id),failed:(run.items||[]).filter(i=>i.state==='FAILED').map(i=>({id:i.job_id,message:D.errorCode(i.code,502,'/api/matching/tasks')+D.matchingDiagnostic(i.diagnostic)})),done:(run.items||[]).filter(i=>['SUCCEEDED','REUSED'].includes(i.state)).length,calls:run.calls||0};}
 function render(run,runs,{esc,D},notice=''){
  if(!run)return notice?`<section class="match-progress" role="status">${esc(notice)}</section>`:'';
  const p=progress(run,D),live=active(run),canResume=!live&&!['COMPLETED','CANCELLED'].includes(run.state);
  return `<section class="match-progress durable-progress" aria-label="分析任务"><div class="section-title"><div><strong>${run.kind==='COMPANY'?'同公司比较 · ':''}${esc(states[run.state]||'任务状态待刷新')}</strong><p class="meta">完成 ${p.done} / ${run.items.length} 个 · 待处理 ${p.pending.length} 个 · 失败 ${p.failed.length} 个 · 调用 ${p.calls} 次</p></div><span class="pill">进度已保存</span></div>${notice?`<p role="status">${esc(notice)}</p>`:''}<div class="actions">${run.kind==='COMPANY'&&run.state==='COMPLETED'?'<button id="match-task-company-result" class="btn btn-primary">查看本轮公司比较</button>':''}${canResume&&p.pending.length?`<button id="match-continue" class="btn btn-small">核对并继续（${p.pending.length}）</button>`:''}${canResume&&p.failed.length?`<button id="match-retry" class="btn btn-small">核对并重试失败项（${p.failed.length}）</button>`:''}${run.state==='RUNNING'?'<button id="match-pause" class="btn btn-small">暂停后续分析</button>':''}${!['COMPLETED','CANCELLED'].includes(run.state)?'<button id="match-task-cancel" class="btn btn-small">取消本轮</button>':''}<button id="match-task-events" class="btn btn-small">查看处理记录</button></div><p class="meta">关闭网页后，已授权的本轮任务继续处理。服务中断后不会自动重新调用模型；继续或重试前需要核对外发资料。</p>${p.failed.length?`<details><summary>失败项与处理建议</summary><ul>${p.failed.map(f=>`<li>${esc(run.items.find(i=>i.job_id===f.id)?.job?.title||'岗位')}：${esc(f.message)}</li>`).join('')}</ul></details>`:''}<div id="match-task-events-box"></div>${runs.length>1?`<details><summary>最近分析任务（${runs.length} 轮）</summary><div class="task-history">${runs.map(v=>`<button class="text-btn" data-match-task="${esc(v.id)}" ${live?'disabled':''}>${esc(D.date(v.created_at))} · ${esc(states[v.state]||v.state)} · ${v.items.length} 个岗位</button>`).join('')}</div></details>`:''}</section>`;
 }
 function traceHTML(events,{esc,D}){const stages={PREPARE:'准备资料',ANALYZE:'整体岗位分析',COMPANY:'同公司整体比较',EXTRACT:'提取岗位要求',COMPARE:'匹配个人资料',SAVE:'保存结果'};return `<details open><summary>本轮处理记录</summary>${events.length?`<ol class="task-trace">${[...events].reverse().map(e=>`<li><b>${esc(stages[e.stage]||'处理任务')}</b> · ${esc(D.date(e.occurred_at))}${e.duration_ms?' · '+(e.duration_ms/1000).toFixed(2)+' 秒':''}${e.code?'<p>'+esc(D.errorCode(e.code,502,'/api/matching/tasks'))+'</p>':''}<small>任务编号：${esc(e.run_id)}${e.request_id?' · 请求编号：'+esc(e.request_id):''}</small></li>`).join('')}</ol>`:'<p class="meta">任务还没有处理记录。</p>'}</details>`;}
 const api={active,progress,render,traceHTML};if(typeof module==='object'&&module.exports)module.exports=api;root.CampusMatchTasks=api;return api;
})(typeof window==='undefined'?globalThis:window);
