'use strict';
const CampusDecision=(function(root){
  const kinds={VERIFY:'核对条件',EVIDENCE:'补充依据',LEARN:'学习差距',DEEPEN:'深化经验',REHEARSE:'演练讲解'};
  const categories={QUALIFICATION:'投递资格',REQUIRED:'必需能力',RESPONSIBILITY:'工作内容',BONUS:'加分项',SOFT:'软性要求'};
  const states={BASIC:'待深度分析',STALE:'分析待更新',ANALYZED:'已分析'};
  const results={DIRECT:'直接匹配',PARTIAL:'部分匹配',TRANSFERABLE:'可迁移经验',MISMATCH:'明确不符合',NO_EVIDENCE:'暂无充分依据'};
  function progressKey(user,plan){return 'campustrace:preparation:v1:'+encodeURIComponent(user)+':'+encodeURIComponent(plan.job.id);}
  function readProgress(user,plan){
    if(plan.state!=='ANALYZED'||!plan.input_key)return new Set();
    try{const v=JSON.parse(root.localStorage.getItem(progressKey(user,plan))||'null');if(v?.input_key===plan.input_key&&v?.version===plan.version&&v?.analyzed_at===plan.analyzed_at&&Array.isArray(v.done)){const allowed=new Set(plan.tasks.map(t=>t.id));return new Set(v.done.filter(id=>allowed.has(id)));}}catch{}
    return new Set();
  }
  function saveProgress(user,plan,done){
    if(plan.state!=='ANALYZED'||!plan.input_key)return false;
    try{const allowed=new Set(plan.tasks.map(t=>t.id));root.localStorage.setItem(progressKey(user,plan),JSON.stringify({input_key:plan.input_key,version:plan.version,analyzed_at:plan.analyzed_at,done:[...done].filter(id=>allowed.has(id))}));return true;}catch{return false;}
  }
  function taskEvidence(task,{esc}){
    return `<details class="prep-evidence"><summary>核对要求与资料依据</summary>${(task.requirements||[]).map(r=>`<p><b>${esc(r.text)}</b>${r.id===task.selected_requirement_id&&task.requirements.length>1?' · 所选方向':''}</p><blockquote>${esc(r.excerpt)}</blockquote>${r.group_excerpt?`<small>任选依据：${esc(r.group_excerpt)}</small>`:''}`).join('')}${task.explanation?`<p class="meta">分析说明：${esc(task.explanation)}</p>`:''}<h5>已确认的个人依据</h5>${task.evidence?.length?task.evidence.map(e=>`<p class="meta">${esc(e.project_name||'求职资料')} · ${esc(e.kind==='LIMITATION'?'已确认局限':e.kind==='IMPLEMENTED'?'项目实现':'资料事实')}</p><blockquote>${esc(e.excerpt)}</blockquote>`).join(''):'<p class="meta">当前没有可引用的个人依据；先核对真实经历，再补充资料。</p>'}</details>`;
  }
  function renderPreparation(plan,{esc,D},done=new Set()){
    const tasks=plan.tasks||[],ready=plan.state==='ANALYZED'&&!!plan.input_key;
    return `<section class="preparation"><div class="decision-intro"><span class="eyebrow">岗位准备清单</span><h3>把分析变成下一步行动</h3><p>按核心差距、已有经验和加分项安排准备。每项都可以展开核对原文与个人依据。</p></div>${plan.evidence_reviews?`<p class="pending-note">${Number(plan.evidence_reviews)} 项错误能力引用已撤销，按暂无依据安排核对；不会计为已掌握。</p>`:''}${plan.notice?`<p class="pending-note">${esc(plan.notice)}</p>`:''}${!ready?'<button class="btn btn-primary" data-prep-analyze>返回分析这份岗位</button>':`<p class="meta">基于 ${esc(D.date(plan.analyzed_at))} 的分析 · 核心匹配度 ${plan.score==null?'暂无可靠评分':Number(plan.score).toFixed(1)+' / 100'} · 依据覆盖 ${Number(plan.coverage).toFixed(1)}%</p>${plan.score==null?'<p class="pending-note">核心要求依据不足，准备项用于核对和补充资料，暂不形成可靠评分。</p>':''}${tasks.length?`<div class="prep-progress"><strong data-prep-count>已完成 ${done.size} / ${tasks.length}</strong><span data-prep-storage>勾选进度保存在当前浏览器；资料、岗位或分析变化后需重新核对。</span></div><div class="prep-list">${tasks.map(t=>`<article class="prep-task ${done.has(t.id)?'is-done':''}"><div class="prep-task-head"><label class="check"><input type="checkbox" data-prep-task="${esc(t.id)}" ${done.has(t.id)?'checked':''}><span><small>${esc(categories[t.category]||'岗位要求')} · ${t.priority===1?'优先处理':t.priority===3?'后续准备':'继续准备'}</small><b>${esc(t.title)}</b></span></label><span class="pill">${esc(kinds[t.kind]||'核对')}</span></div><p>${esc(t.action)}</p>${t.result?`<p class="meta">当前结论：${esc(results[t.result]||D.label('eligibility',t.result))}</p>`:''}${taskEvidence(t,{esc})}</article>`).join('')}</div>`:''}`}${plan.history_topics?.length?`<details class="prep-history"><summary>历史面试复盘 · ${plan.history_topics.length} 个待加强知识点</summary><p class="meta">来自你的历史复盘，不等同于本岗位的能力缺口。</p><ul>${plan.history_topics.map(t=>`<li>${esc(t.topic)}${t.occurrence_count?` · ${Number(t.occurrence_count)} 次提及`:''}</li>`).join('')}</ul>${plan.history_truncated?'<p class="meta">此处显示前 50 项，可在待加强知识点查看完整记录。</p>':''}</details>`:''}<p class="form-note">复用已保存的分析，不发送资料，也不额外调用模型。完成勾选不会修改技能、项目事实或投递记录。</p></section>`;
  }
  function renderCompany(report,{esc,D}){
    const status={NONE:'暂不能可靠推荐',READY:'优先查看',PARTIAL:'已分析范围的优先候选',TIED:'多个岗位并列候选'},scope={ALL:'本地该公司可见岗位',FILTERED:'本次筛选范围',SELECTED:'本次已选岗位'};
    return `<section class="company-report"><div class="decision-summary"><div><span class="eyebrow">${esc(scope[report.scope]||'本次范围')}</span><h3>${esc(status[report.recommendation]||'对比结果')}</h3><p>${Number(report.total)} 个岗位 · 已分析 ${Number(report.analyzed)} · 待分析 ${Number(report.pending)} · 待更新 ${Number(report.stale)}</p></div><small>生成于 ${esc(D.date(report.generated_at))}</small></div><ul class="decision-reasons">${(report.reasons||[]).map(r=>`<li>${esc(r)}</li>`).join('')}</ul>${report.jobs?.length?`<p class="comparison-swipe">左右滑动表格，查看完整对比与准备入口。</p><div class="table-wrap company-comparison"><table><thead><tr><th>岗位</th><th>核心匹配 / 覆盖</th><th>资格与偏好</th><th>主要依据</th><th>下一步</th></tr></thead><tbody>${report.jobs.map(row=>`<tr class="${row.recommended?'is-recommended':''}"><td>${row.recommended?'<span class="pill positive">优先候选</span>':''}<b>${esc(row.job.title)}</b><small>${esc((row.job.locations||[]).join(' / '))}</small><small>${esc(states[row.state]||row.state)}</small>${row.evidence_reviews?`<small class="decision-warning">${Number(row.evidence_reviews)} 项错误引用已撤销，请核对逐项依据。</small>`:''}${row.blocked_reason?`<small class="decision-warning">${esc(row.blocked_reason)}</small>`:''}</td><td>${row.score==null?'<b>暂无可靠评分</b>':`<b class="decision-score">${Number(row.score).toFixed(1)}</b><small>核心依据覆盖 ${Number(row.coverage).toFixed(1)}%</small>`}${row.state==='ANALYZED'&&row.score==null?`<small>覆盖 ${Number(row.coverage).toFixed(1)}%</small>`:''}</td><td>${row.state==='ANALYZED'?`<b>${esc(D.label('eligibility',row.eligibility))}</b>`:'<b>待分析核对</b>'}<small>${esc(row.direction)}</small><small>${esc(row.city_preference)} · ${esc(row.type_preference)}</small></td><td>${row.state==='ANALYZED'?`<small>${row.strengths?.length?'已有依据：'+esc(row.strengths[0].title):'尚无直接匹配的主要依据'}</small><small>${row.gaps?.length?'优先核对：'+esc(row.gaps[0].title):'暂无已识别主要差距'}</small><details><summary>展开主要依据（各最多 3 项）</summary>${(row.sections||[]).map(s=>`<p class="meta">${esc(categories[s.category])}：${Number(s.known)} / ${Number(s.total)} 项有依据</p>`).join('')}${[...(row.strengths||[]),...(row.gaps||[])].map(t=>`<p><b>${esc(t.title)}</b> · ${esc(results[t.result]||'待核对')}</p>${taskEvidence(t,{esc})}`).join('')}</details>`:'<small>深度分析后可对比</small>'}</td><td><button class="btn btn-small" data-compare-detail="${esc(row.job.id)}">查看岗位</button><button class="btn btn-small" data-compare-prepare="${esc(row.job.id)}" ${row.state==='ANALYZED'?'':'disabled'}>准备清单</button></td></tr>`).join('')}</tbody></table></div>`:'<p class="empty">此范围没有可对比的岗位。</p>'}<details class="decision-method"><summary>推荐如何计算</summary><p class="meta">关闭、忽略和明确不符合投递条件的岗位不推荐。仅使用当前分析、核心依据覆盖至少 60% 且可评分的岗位；依次考虑意向方向、资格状态、核心技术匹配度、覆盖度、城市、岗位类型和加分项依据。并列保留多个候选；分数不是录用概率。工作内容和软性要求分别展示，不混入核心分数。</p></details><p class="form-note">结论仅针对上面列出的范围。仍有待分析或待更新岗位时，不能据此认定是全公司最匹配的岗位；实际限投规则请核对公司官网。</p></section>`;
  }
  const api={renderPreparation,renderCompany,readProgress,saveProgress,progressKey};
  if(typeof module==='object'&&module.exports)module.exports=api;
  root.CampusDecision=api;return api;
})(typeof window==='undefined'?globalThis:window);
