(function(root){
'use strict';
const example={code:'package exercise\n\n// Deduplicate 返回按首次出现顺序去重的编号。\nfunc Deduplicate(ids []int) []int {\n    seen := make(map[int]bool)\n    out := make([]int, 0, len(ids))\n    for _, id := range ids {\n        if !seen[id] {\n            seen[id] = true\n            out = append(out, id)\n        }\n    }\n    return out\n}\n',tests:'package exercise\n\nimport ("reflect"; "testing")\n\nfunc TestDeduplicate(t *testing.T) {\n    got := Deduplicate([]int{3, 1, 3, 2, 1})\n    want := []int{3, 1, 2}\n    if !reflect.DeepEqual(got, want) {\n        t.Fatalf("got %v, want %v", got, want)\n    }\n}\n'};
const states={RUNNING:'运行中',PASSED:'测试通过',FAILED:'测试未通过',TIMEOUT:'运行超时',OOM:'内存超限',INTERRUPTED:'运行中断',ERROR:'未能完成运行'};
function render(v,esc){return `<article class="card"><h3>${esc(states[v.state]||'未知状态')}</h3><p class="meta">${esc(new Date(v.created_at).toLocaleString('zh-CN'))} · ${Number(v.duration_ms)||0} 毫秒${v.truncated?' · 输出已截短':''}</p><pre class="practice-output">${esc(v.output||'暂时没有输出。')}</pre>${v.code&&v.tests?`<button type="button" data-practice-load="${esc(v.id)}">载入这次代码与测试</button>`:''}</article>`;}
async function page(set,heading,h){const {api,esc,formAction,UserError}=h;const active=h.active||(()=>true);const [caps,runs]=await Promise.all([api('/api/practice/capabilities'),api('/api/practice/runs')]);
 if(!set(`${heading}<details><summary>运行环境</summary><p class="meta">独立容器运行，不联网、不挂载个人文件；限时 45 秒，内存 384 MB。问答查询练习记录时，执行结果会发送给模型。</p></details>${!caps.enabled?'<div class="callout">练习组件尚未启动。在项目入口运行 <code>campustrace practice start</code> 后重新打开此页。</div>':''}<form id="practice-form" novalidate><div class="actions"><button id="practice-example" type="button">载入 Go 去重示例</button></div><label>实现代码（package exercise）<textarea name="code" class="code-editor" rows="14" required maxlength="24000"></textarea></label><label>测试代码（至少一个 Test 用例）<textarea name="tests" class="code-editor" rows="12" required maxlength="24000"></textarea></label><button ${caps.enabled?'':'disabled'}>运行测试</button><p id="practice-status" role="status"></p></form><div id="practice-result"></div><details><summary>最近的练习记录</summary><div id="practice-history">${runs.map(v=>render(v,esc)).join('')||'<p>还没有运行过练习。</p>'}</div></details>`))return;
 let history=runs;const loadHistory=()=>{for(const b of document.querySelectorAll('[data-practice-load]'))b.onclick=()=>{const v=history.find(x=>x.id===b.dataset.practiceLoad);if(v){form.elements.code.value=v.code;form.elements.tests.value=v.tests;form.elements.code.dispatchEvent(new Event('input',{bubbles:true}));form.elements.code.focus();}};};
 const form=document.querySelector('#practice-form');const drafts=root.CampusNavigation?.forms(document,{selector:'#practice-form'});drafts?.restore();root.CampusNavigation?.register({active,dirty:()=>drafts?.dirty()||false});
 document.querySelector('#practice-example').onclick=()=>{form.elements.code.value=example.code;form.elements.tests.value=example.tests;form.elements.code.dispatchEvent(new Event('input',{bubbles:true}));};
 // Preserve the same nonce for a network retry of unchanged code; a completed
 // run or edited code receives a new nonce. The server never auto-replays code.
 loadHistory();let retry=null;
 formAction('#practice-form',async data=>{const code=String(data.get('code')),tests=String(data.get('tests'));if(new TextEncoder().encode(code).length>24000||new TextEncoder().encode(tests).length>24000)throw new UserError('实现和测试各需控制在 24000 字节内。');if(!caps.enabled)return;const fingerprint=code+'\n'+tests;if(!retry||retry.fingerprint!==fingerprint)retry={fingerprint,key:crypto.randomUUID()};document.querySelector('#practice-status').textContent='正在运行，首次编译可能需要稍等…';const point=drafts?.savepoint('#practice-form');try{const out=await api('/api/practice/runs','POST',{code,tests,request_key:retry.key});if(!active())return;document.querySelector('#practice-result').innerHTML=render(out,esc);document.querySelector('#practice-status').textContent=states[out.state]||'已返回结果';if(out.state!=='RUNNING'){retry=null;drafts?.saved('#practice-form',point);}history=await api('/api/practice/runs');if(active()){document.querySelector('#practice-history').innerHTML=history.map(v=>render(v,esc)).join('');loadHistory();}}catch(e){if(active())document.querySelector('#practice-status').textContent='未收到完整结果。重试会先查询同一次运行的回执。';throw e;}});
}
root.CampusPractice={page,render,example,states};if(typeof module!=='undefined')module.exports=root.CampusPractice;
})(typeof window!=='undefined'?window:globalThis);
