'use strict';
const radarKinds={NEW_JOB:'新增岗位',JOB_CONTENT_CHANGED:'招聘内容变化',JOB_STATUS_CHANGED:'岗位状态变化',DEADLINE_CHANGED:'截止时间变化'};
function radarCards(rows){return rows.length?rows.map(v=>`<article class="radar-card"><div class="card-top"><span>${esc(D.text(v.job.company))}</span>${pill(v.job.current_status)}</div><h3><button class="job-link" data-job="${esc(v.job.id)}">${esc(D.text(v.job.title))}</button></h3><p class="meta">${esc((v.job.locations||[]).map(D.text).join('、')||'地点待确认')} · ${esc(D.label('eligibility',v.eligibility))}</p>${v.deadline?`<p class="deadline">截止：${esc(D.date(v.deadline))}</p>`:''}${v.ranking?.input_identity?`<p>优先级 ${Number(v.ranking.score).toFixed(1)} <span class="meta">· ${v.disposition==='SAVED'?'已收藏 · ':''}依据详见岗位评分</span></p>`:''}<div class="quick-actions"><button data-pref="SAVED" data-id="${esc(v.job.id)}">稍后看</button><button data-pref="IGNORED" data-id="${esc(v.job.id)}">忽略</button><button data-apply="PLANNED" data-id="${esc(v.job.id)}">准备投递</button><button data-apply="APPLIED" data-id="${esc(v.job.id)}">已投递</button></div></article>`).join(''):empty('当前没有需要处理的岗位。可先关注招聘来源，或完善求职资料。');}
function radarChanges(rows){return rows.length?rows.map(c=>`<article class="change-row"><span class="change-dot" aria-hidden="true"></span><div><b>${esc(radarKinds[c.type]||'岗位变化')}</b><button class="job-link" data-job="${esc(c.job_id)}">${esc(D.text(c.title))}</button>${c.type==='JOB_STATUS_CHANGED'?`<small>${esc(D.label('job',c.from))} → ${esc(D.label('job',c.to))}</small>`:''}<small>${esc(D.date(c.created_at))}</small></div></article>`).join(''):empty('这段时间还没有岗位变化。');}
function bindRadar(box,refresh){
 for(const b of box.querySelectorAll('[data-job]'))b.onclick=()=>detail(b.dataset.job).catch(fail);
 for(const b of box.querySelectorAll('[data-pref]'))b.onclick=async()=>{b.disabled=true;try{await api('/api/jobs/'+b.dataset.id+'/preference','PUT',{disposition:b.dataset.pref});await refresh();}catch(e){fail(e);b.disabled=false;}};
 for(const b of box.querySelectorAll('[data-apply]'))b.onclick=async()=>{b.disabled=true;try{
 const apps=await api('/api/applications');let app=apps.find(a=>a.job_id===b.dataset.id);
 if(!app)app=await api('/api/applications','POST',{job_id:b.dataset.id});
 if(b.dataset.apply==='PLANNED'&&app.current_state!=='PLANNED')throw new UserError('当前已有投递进展，请在投递进展中查看；结束的投递不能重新开启。');
 if(b.dataset.apply==='APPLIED'&&app.current_state==='PLANNED')await api('/api/applications/transition','POST',{application_id:app.id,state:'APPLIED',version:app.version});
 else if(b.dataset.apply==='APPLIED'&&app.current_state!=='APPLIED')throw new UserError('当前投递已进入后续阶段，请在投递进展中查看。');
 await refresh();$('#notice').textContent=b.dataset.apply==='APPLIED'?'已记录投递。':'已加入投递计划。';
 }catch(e){fail(e);b.disabled=false;}};
}
async function radarPage(name,set,box,query){
 if(name==='radar'){
 const v=await api('/api/radar/digest');const metrics=[['今日新增',v.counts.new_jobs],['优先投递',v.counts.recommended_jobs],['7 天内截止',v.counts.closing_soon],['状态变化',v.counts.status_changes],['本周面试',v.counts.upcoming_interviews]];
 if(!set(`<div class="radar-hero"><div><p class="eyebrow">CampusTrace · Job Radar</p><h1>我的校招雷达</h1><p>招聘发生了什么，今天从这里开始。</p><small>更新于 ${esc(D.date(v.as_of))} · 新增与变化统计过去 24 小时${v.truncated?' · 首页展示前 5 个岗位，更多请进入分类查看':''}</small></div><div class="actions"><button data-go="watches">关注源</button><button data-go="notifications">通知收件箱</button></div></div><div class="radar-metrics">${metrics.map(([label,n])=>`<div><span>${esc(label)}</span><strong>${n}</strong></div>`).join('')}</div><div class="section-heading"><h2>今天最值得投</h2><button data-go="jobs">查看岗位库 →</button></div><p class="meta">按当前资格与可解释评分排序；已投递、忽略及终态记录不进入推荐。</p><div class="radar-grid">${radarCards(v.recommended_jobs.slice(0,6))}</div><div class="radar-columns"><section><div class="section-heading"><h2>最近变化</h2><button data-go="changes">过去 7 天 →</button></div>${radarChanges(v.recent_changes.slice(0,8))}</section><section><div class="section-heading"><h2>即将截止</h2><button data-go="closing">查看截止雷达 →</button></div>${radarCards(v.closing_soon.slice(0,3))}</section></div><h2>本周安排</h2>${v.upcoming_interviews.length?table(v.upcoming_interviews,['round','scheduled_at','result','notes']):empty('未来 7 天暂无面试安排。')}<h2>今日新发现</h2><div class="radar-grid">${radarCards(v.new_jobs.slice(0,6))}</div>`))return;
 for(const b of box.querySelectorAll('[data-go]'))b.onclick=()=>page(b.dataset.go).catch(fail);bindRadar(box,()=>page('radar'));return;
 }
 if(name==='changes'||name==='closing'){
 const days=Number(query)||(name==='changes'?7:7),values=name==='changes'?[1,7]:[3,7,14];const rows=await api('/api/radar/'+name+'?days='+days);
 if(!set(`<h2>${name==='changes'?'最近变化':'截止雷达'}</h2><div class="actions">${values.map(n=>`<button data-days="${n}" aria-pressed="${days===n}">${name==='changes'?'过去':'未来'} ${n} 天</button>`).join('')}</div>${name==='changes'?'<p class="meta">按发生时间展示最近 100 条变化。</p>'+radarChanges(rows):'<div class="radar-grid">'+radarCards(rows)+'</div>'}`))return;
 for(const b of box.querySelectorAll('[data-days]'))b.onclick=()=>page(name,b.dataset.days).catch(fail);bindRadar(box,()=>page(name,days));return;
 }
 if(name==='watches'){
 const [watches,sources]=await Promise.all([api('/api/watches'),api('/api/sources')]);const supported=sources.filter(s=>s.adapter);const sourceName=id=>sources.find(s=>s.id===id)?.name||id;
 const watchForm=(v={})=>`<div class="form-grid">${v.id?`<input type="hidden" name="source_id" value="${esc(v.source_id)}">`:`<label>招聘来源<select name="source_id" required>${supported.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} · ${esc(s.adapter)}</option>`).join('')}</select></label>`}${input('check_interval','检查间隔（分钟）',(v.check_interval||3600)/60,'number','required min="5" max="10080"')}${input('keyword','标题或地点包含（可选）',v.keyword||'','text','maxlength="100"')}</div><label class="check"><input type="checkbox" name="enabled" ${v.enabled===false?'':'checked'}>启用周期检查</label><button>${v.id?'保存关注设置':'开始关注'}</button>`;
 const outcomes={PENDING:'等待检查',PROCESSING:'正在核验岗位',SUCCESS:'检查完成',PARTIAL_FAILURE:'部分岗位获取失败',DISCOVERY_FAILED:'来源暂时无法读取',FAILED:'本次检查失败'};
 if(!set(`<h2>关注源</h2><p>定期发现岗位，并重新核验已发现的招聘页面。过滤词按标题或地点匹配，留空关注该来源全部岗位。</p>${supported.length?`<form id="watch-create" novalidate>${watchForm()}</form>`:empty('尚未登记可监控来源。请由维护者登记公开招聘平台与企业标识；已有岗位仍可手动导入。')}<h3>我的关注</h3>${watches.length?watches.map(v=>`<article class="card"><h3>${esc(sourceName(v.source_id))} <span class="meta">${v.enabled?'已启用':'已暂停'}</span></h3><p>${esc(outcomes[v.last_outcome]||'状态待确认')}</p><p class="meta">上次检查：${v.last_checked_at?esc(D.date(v.last_checked_at)):'尚未检查'} · 下次检查：${v.enabled?esc(D.date(v.next_check_at)):'已暂停'}</p><form id="watch-${v.id}" novalidate>${watchForm(v)}</form><button data-delete-watch="${v.id}">删除关注</button></article>`).join(''):empty('还没有关注来源。选择上方招聘来源后，雷达会按间隔自动检查。')}`))return;
 const save=async(data,id)=>{await api('/api/watches'+(id?'/'+id:''),id?'PUT':'POST',{source_id:data.get('source_id'),check_interval:Number(data.get('check_interval'))*60,keyword:data.get('keyword'),enabled:data.has('enabled')});await page('watches');};
 if(supported.length)formAction('#watch-create',data=>save(data));for(const v of watches)formAction('#watch-'+v.id,data=>save(data,v.id));for(const b of box.querySelectorAll('[data-delete-watch]'))b.onclick=async()=>{try{await api('/api/watches/'+b.dataset.deleteWatch,'DELETE');await page('watches');}catch(e){fail(e);}};return;
 }
 if(name==='notifications'){
 const rows=await api('/api/notifications');if(!set(`<h2>通知收件箱</h2><p>新优先岗位、状态变化、截止提醒与面试安排。相同事实只提醒一次；截止时间改变会重新计算提醒。</p><button id="refresh-inbox">更新提醒</button>${rows.length?rows.map(n=>`<article class="card ${n.read_at?'read-notification':''}"><h3>${esc(n.title)} ${n.read_at?'':'<span class="unread">未读</span>'}</h3><p>${esc(n.body)}</p><small>${esc(D.date(n.created_at))}</small><div class="actions">${n.entity_type==='JOB'?`<button data-job="${esc(n.entity_id)}">查看岗位</button>`:''}${!n.read_at?`<button data-read="${esc(n.id)}">标为已读</button>`:''}</div></article>`).join(''):empty('暂时没有通知。关注来源后，有值得处理的变化会显示在这里。')}`))return;
 $('#refresh-inbox').onclick=async()=>{try{await api('/api/notifications/refresh','POST',{});await page('notifications');}catch(e){fail(e);}};for(const b of box.querySelectorAll('[data-read]'))b.onclick=async()=>{try{await api('/api/notifications/'+b.dataset.read+'/read','POST',{});await page('notifications');}catch(e){fail(e);}};bindRadar(box,()=>page('notifications'));return;
 }
 if(name==='preferences'){
 const rows=await api('/api/preferences');if(!set(`<h2>稍后看与忽略</h2>${rows.filter(v=>v.disposition!=='NONE').map(v=>`<article class="card"><button data-job="${esc(v.job_id)}">查看岗位</button><span>${v.disposition==='SAVED'?'稍后看':'已忽略'}</span><button data-pref="NONE" data-id="${esc(v.job_id)}">恢复默认</button></article>`).join('')||empty('还没有收藏或忽略的岗位。')}`))return;bindRadar(box,()=>page('preferences'));
 }
}
